/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  ISkill,
} from './global/values/_skillValues.interfaces';


export namespace Components {

  interface MsArcher {
    'agileArcher': number;
    'arrowBarrage': number;
    'arrowStorm': number;
    'arrowStream': number;
    'bowSwing': number;
    'bronzeEagle': number;
    'conditioning': number;
    'eagleClaw': number;
    'eagleGlide': number;
    'eaglesMajesty': number;
    'editable': boolean;
    'evasiveSalvo': number;
    'iceArrow': number;
    'precisionShooter': number;
    'rapidShot': number;
    'screwdriverShot': number;
    'sharpEyes': number;
    'snipe': number;
  }
  interface MsArcherAttributes extends StencilHTMLAttributes {
    'agileArcher'?: number;
    'arrowBarrage'?: number;
    'arrowStorm'?: number;
    'arrowStream'?: number;
    'bowSwing'?: number;
    'bronzeEagle'?: number;
    'conditioning'?: number;
    'eagleClaw'?: number;
    'eagleGlide'?: number;
    'eaglesMajesty'?: number;
    'editable'?: boolean;
    'evasiveSalvo'?: number;
    'iceArrow'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'precisionShooter'?: number;
    'rapidShot'?: number;
    'screwdriverShot'?: number;
    'sharpEyes'?: number;
    'snipe'?: number;
  }

  interface MsAssassin {
    'darkCloak': number;
    'dash': number;
    'deathSentence': number;
    'editable': boolean;
    'fatalStrikes': number;
    'fragmentedStar': number;
    'luckyStars': number;
    'markOfDeath': number;
    'mirrorImageDarkBlade': number;
    'shadowArts': number;
    'shadowBurst': number;
    'shadowChaser': number;
    'shadowCutter': number;
    'shadowWeb': number;
    'soulGrind': number;
    'starChaser': number;
    'starFlurry': number;
    'thrownWeaponMastery': number;
  }
  interface MsAssassinAttributes extends StencilHTMLAttributes {
    'darkCloak'?: number;
    'dash'?: number;
    'deathSentence'?: number;
    'editable'?: boolean;
    'fatalStrikes'?: number;
    'fragmentedStar'?: number;
    'luckyStars'?: number;
    'markOfDeath'?: number;
    'mirrorImageDarkBlade'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'shadowArts'?: number;
    'shadowBurst'?: number;
    'shadowChaser'?: number;
    'shadowCutter'?: number;
    'shadowWeb'?: number;
    'soulGrind'?: number;
    'starChaser'?: number;
    'starFlurry'?: number;
    'thrownWeaponMastery'?: number;
  }

  interface MsBerserker {
    'adrenalineRush': number;
    'bloodPrice': number;
    'bloodlust': number;
    'darkAura': number;
    'darkBreaker': number;
    'darkMight': number;
    'deathSpin': number;
    'deepWounds': number;
    'earthquake': number;
    'editable': boolean;
    'greatswordMastery': number;
    'groundBreaker': number;
    'inhumanEndurance': number;
    'intimidation': number;
    'ragingSlash': number;
    'voidSlash': number;
    'warriorsInstinct': number;
    'xSlash': number;
  }
  interface MsBerserkerAttributes extends StencilHTMLAttributes {
    'adrenalineRush'?: number;
    'bloodPrice'?: number;
    'bloodlust'?: number;
    'darkAura'?: number;
    'darkBreaker'?: number;
    'darkMight'?: number;
    'deathSpin'?: number;
    'deepWounds'?: number;
    'earthquake'?: number;
    'editable'?: boolean;
    'greatswordMastery'?: number;
    'groundBreaker'?: number;
    'inhumanEndurance'?: number;
    'intimidation'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'ragingSlash'?: number;
    'voidSlash'?: number;
    'warriorsInstinct'?: number;
    'xSlash'?: number;
  }

  interface MsChart {
    'msClass': string;
  }
  interface MsChartAttributes extends StencilHTMLAttributes {
    'msClass'?: string;
  }

  interface MsHeavyGunner {
    'advancedBullets': number;
    'advancedMissiles': number;
    'advancedPulseWeapons': number;
    'blastChargeKit': number;
    'bulletSpray': number;
    'editable': boolean;
    'electricBlast': number;
    'gatlingFire': number;
    'homingMissiles': number;
    'jetBoots': number;
    'lockOn': number;
    'mBomb': number;
    'magneticBomb': number;
    'medKit': number;
    'reload': number;
    'rocketLauncher': number;
    'stunGrenades': number;
    'suborbitalBombardment': number;
  }
  interface MsHeavyGunnerAttributes extends StencilHTMLAttributes {
    'advancedBullets'?: number;
    'advancedMissiles'?: number;
    'advancedPulseWeapons'?: number;
    'blastChargeKit'?: number;
    'bulletSpray'?: number;
    'editable'?: boolean;
    'electricBlast'?: number;
    'gatlingFire'?: number;
    'homingMissiles'?: number;
    'jetBoots'?: number;
    'lockOn'?: number;
    'mBomb'?: number;
    'magneticBomb'?: number;
    'medKit'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'reload'?: number;
    'rocketLauncher'?: number;
    'stunGrenades'?: number;
    'suborbitalBombardment'?: number;
  }

  interface MsKnight {
    'bulwark': number;
    'crossCut': number;
    'defenderOfTheFaith': number;
    'divineStrike': number;
    'drillThrust': number;
    'editable': boolean;
    'ironDefense': number;
    'ironShield': number;
    'longswordMastery': number;
    'shieldBooster': number;
    'shieldCharge': number;
    'shieldMastery': number;
    'shieldToss': number;
    'shieldWall': number;
    'stingingFlurry': number;
    'tornadoSlash': number;
    'typhoonSlash': number;
    'warhorn': number;
  }
  interface MsKnightAttributes extends StencilHTMLAttributes {
    'bulwark'?: number;
    'crossCut'?: number;
    'defenderOfTheFaith'?: number;
    'divineStrike'?: number;
    'drillThrust'?: number;
    'editable'?: boolean;
    'ironDefense'?: number;
    'ironShield'?: number;
    'longswordMastery'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'shieldBooster'?: number;
    'shieldCharge'?: number;
    'shieldMastery'?: number;
    'shieldToss'?: number;
    'shieldWall'?: number;
    'stingingFlurry'?: number;
    'tornadoSlash'?: number;
    'typhoonSlash'?: number;
    'warhorn'?: number;
  }

  interface MsPriest {
    'angelicRay': number;
    'celestialBlessings': number;
    'celestialGuardian': number;
    'celestialLight': number;
    'disciple': number;
    'editable': boolean;
    'healingMastery': number;
    'healingPrayer': number;
    'heavenlyWings': number;
    'holyBlast': number;
    'holyRelic': number;
    'holySymbol': number;
    'sanctuary': number;
    'scepterMastery': number;
    'scourgingWave': number;
    'shieldOfTheArchon': number;
    'smitingAura': number;
    'steadfastFaith': number;
  }
  interface MsPriestAttributes extends StencilHTMLAttributes {
    'angelicRay'?: number;
    'celestialBlessings'?: number;
    'celestialGuardian'?: number;
    'celestialLight'?: number;
    'disciple'?: number;
    'editable'?: boolean;
    'healingMastery'?: number;
    'healingPrayer'?: number;
    'heavenlyWings'?: number;
    'holyBlast'?: number;
    'holyRelic'?: number;
    'holySymbol'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'sanctuary'?: number;
    'scepterMastery'?: number;
    'scourgingWave'?: number;
    'shieldOfTheArchon'?: number;
    'smitingAura'?: number;
    'steadfastFaith'?: number;
  }

  interface MsRuneblade {
    'bladeChasm': number;
    'bladeMastery': number;
    'blink': number;
    'echoingBlade': number;
    'editable': boolean;
    'elementalPotency': number;
    'flameSigil': number;
    'flurry': number;
    'frostSigil': number;
    'gravityRune': number;
    'honingRunes': number;
    'illusoryBlades': number;
    'impact': number;
    'runeBalance': number;
    'runeFocus': number;
    'stormSigil': number;
    'wardingRune': number;
    'whirlingBlades': number;
  }
  interface MsRunebladeAttributes extends StencilHTMLAttributes {
    'bladeChasm'?: number;
    'bladeMastery'?: number;
    'blink'?: number;
    'echoingBlade'?: number;
    'editable'?: boolean;
    'elementalPotency'?: number;
    'flameSigil'?: number;
    'flurry'?: number;
    'frostSigil'?: number;
    'gravityRune'?: number;
    'honingRunes'?: number;
    'illusoryBlades'?: number;
    'impact'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'runeBalance'?: number;
    'runeFocus'?: number;
    'stormSigil'?: number;
    'wardingRune'?: number;
    'whirlingBlades'?: number;
  }

  interface MsSoulBinder {
    'animusFocus': number;
    'chainExplosion': number;
    'chainSpear': number;
    'cycloneBomber': number;
    'editable': boolean;
    'electricEnergyDischarge': number;
    'energyStream': number;
    'expansionBall': number;
    'flashStrike': number;
    'illusion': number;
    'lifeString': number;
    'mantraRelease': number;
    'narubashanLiberation': number;
    'orbMastery': number;
    'rayStorm': number;
    'shootingStar': number;
    'splitBarrier': number;
    'zoneOfRenewal': number;
  }
  interface MsSoulBinderAttributes extends StencilHTMLAttributes {
    'animusFocus'?: number;
    'chainExplosion'?: number;
    'chainSpear'?: number;
    'cycloneBomber'?: number;
    'editable'?: boolean;
    'electricEnergyDischarge'?: number;
    'energyStream'?: number;
    'expansionBall'?: number;
    'flashStrike'?: number;
    'illusion'?: number;
    'lifeString'?: number;
    'mantraRelease'?: number;
    'narubashanLiberation'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'orbMastery'?: number;
    'rayStorm'?: number;
    'shootingStar'?: number;
    'splitBarrier'?: number;
    'zoneOfRenewal'?: number;
  }

  interface MsThief {
    'bladeDance': number;
    'cunningTactics': number;
    'deftCombatant': number;
    'doubleSlash': number;
    'editable': boolean;
    'haste': number;
    'mesoguardPlus': number;
    'mindBreaker': number;
    'mindStealer': number;
    'poisonEdge': number;
    'poisonVial': number;
    'quickStep': number;
    'retaliation': number;
    'ruthlessGuile': number;
    'somersaultKick': number;
    'spiritThief': number;
    'surpriseAttack': number;
    'viciousCuts': number;
  }
  interface MsThiefAttributes extends StencilHTMLAttributes {
    'bladeDance'?: number;
    'cunningTactics'?: number;
    'deftCombatant'?: number;
    'doubleSlash'?: number;
    'editable'?: boolean;
    'haste'?: number;
    'mesoguardPlus'?: number;
    'mindBreaker'?: number;
    'mindStealer'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'poisonEdge'?: number;
    'poisonVial'?: number;
    'quickStep'?: number;
    'retaliation'?: number;
    'ruthlessGuile'?: number;
    'somersaultKick'?: number;
    'spiritThief'?: number;
    'surpriseAttack'?: number;
    'viciousCuts'?: number;
  }

  interface MsWizard {
    'arcaneBlast': number;
    'chainLightning': number;
    'cryomancy': number;
    'editable': boolean;
    'electromancy': number;
    'elementalMaster': number;
    'flameTornado': number;
    'flameWave': number;
    'focusSeal': number;
    'iceSpear': number;
    'iceStorm': number;
    'magicArmor': number;
    'manaClaw': number;
    'manaFont': number;
    'phantomClaw': number;
    'pyromancy': number;
    'teleport': number;
    'thunderbolt': number;
  }
  interface MsWizardAttributes extends StencilHTMLAttributes {
    'arcaneBlast'?: number;
    'chainLightning'?: number;
    'cryomancy'?: number;
    'editable'?: boolean;
    'electromancy'?: number;
    'elementalMaster'?: number;
    'flameTornado'?: number;
    'flameWave'?: number;
    'focusSeal'?: number;
    'iceSpear'?: number;
    'iceStorm'?: number;
    'magicArmor'?: number;
    'manaClaw'?: number;
    'manaFont'?: number;
    'onSkillchanged'?: (event: CustomEvent) => void;
    'phantomClaw'?: number;
    'pyromancy'?: number;
    'teleport'?: number;
    'thunderbolt'?: number;
  }

  interface MsExtraCounter {
    'editor'?: string;
  }
  interface MsExtraCounterAttributes extends StencilHTMLAttributes {
    'editor'?: string;
  }

  interface MsExtraOutlet {
    'editor': string;
  }
  interface MsExtraOutletAttributes extends StencilHTMLAttributes {
    'editor'?: string;
  }

  interface MsFooter {}
  interface MsFooterAttributes extends StencilHTMLAttributes {}

  interface MsIcon {
    'name': string;
    'sp': boolean;
  }
  interface MsIconAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'sp'?: boolean;
  }

  interface MsSkillOverlay {
    'level': number;
    'skill': ISkill;
  }
  interface MsSkillOverlayAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'skill'?: ISkill;
  }

  interface MsSkill {
    'column': number;
    'disabled': boolean;
    'level': number;
    'limitReached': boolean;
    'locked': boolean;
    'required': string;
    'row': number;
    'skill': ISkill;
  }
  interface MsSkillAttributes extends StencilHTMLAttributes {
    'column'?: number;
    'disabled'?: boolean;
    'level'?: number;
    'limitReached'?: boolean;
    'locked'?: boolean;
    'onLevelchanged'?: (event: CustomEvent<number>) => void;
    'required'?: string;
    'row'?: number;
    'skill'?: ISkill;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MsArcher': Components.MsArcher;
    'MsAssassin': Components.MsAssassin;
    'MsBerserker': Components.MsBerserker;
    'MsChart': Components.MsChart;
    'MsHeavyGunner': Components.MsHeavyGunner;
    'MsKnight': Components.MsKnight;
    'MsPriest': Components.MsPriest;
    'MsRuneblade': Components.MsRuneblade;
    'MsSoulBinder': Components.MsSoulBinder;
    'MsThief': Components.MsThief;
    'MsWizard': Components.MsWizard;
    'MsExtraCounter': Components.MsExtraCounter;
    'MsExtraOutlet': Components.MsExtraOutlet;
    'MsFooter': Components.MsFooter;
    'MsIcon': Components.MsIcon;
    'MsSkillOverlay': Components.MsSkillOverlay;
    'MsSkill': Components.MsSkill;
  }

  interface StencilIntrinsicElements {
    'ms-archer': Components.MsArcherAttributes;
    'ms-assassin': Components.MsAssassinAttributes;
    'ms-berserker': Components.MsBerserkerAttributes;
    'ms-chart': Components.MsChartAttributes;
    'ms-heavy-gunner': Components.MsHeavyGunnerAttributes;
    'ms-knight': Components.MsKnightAttributes;
    'ms-priest': Components.MsPriestAttributes;
    'ms-runeblade': Components.MsRunebladeAttributes;
    'ms-soul-binder': Components.MsSoulBinderAttributes;
    'ms-thief': Components.MsThiefAttributes;
    'ms-wizard': Components.MsWizardAttributes;
    'ms-extra-counter': Components.MsExtraCounterAttributes;
    'ms-extra-outlet': Components.MsExtraOutletAttributes;
    'ms-footer': Components.MsFooterAttributes;
    'ms-icon': Components.MsIconAttributes;
    'ms-skill-overlay': Components.MsSkillOverlayAttributes;
    'ms-skill': Components.MsSkillAttributes;
  }


  interface HTMLMsArcherElement extends Components.MsArcher, HTMLStencilElement {}
  var HTMLMsArcherElement: {
    prototype: HTMLMsArcherElement;
    new (): HTMLMsArcherElement;
  };

  interface HTMLMsAssassinElement extends Components.MsAssassin, HTMLStencilElement {}
  var HTMLMsAssassinElement: {
    prototype: HTMLMsAssassinElement;
    new (): HTMLMsAssassinElement;
  };

  interface HTMLMsBerserkerElement extends Components.MsBerserker, HTMLStencilElement {}
  var HTMLMsBerserkerElement: {
    prototype: HTMLMsBerserkerElement;
    new (): HTMLMsBerserkerElement;
  };

  interface HTMLMsChartElement extends Components.MsChart, HTMLStencilElement {}
  var HTMLMsChartElement: {
    prototype: HTMLMsChartElement;
    new (): HTMLMsChartElement;
  };

  interface HTMLMsHeavyGunnerElement extends Components.MsHeavyGunner, HTMLStencilElement {}
  var HTMLMsHeavyGunnerElement: {
    prototype: HTMLMsHeavyGunnerElement;
    new (): HTMLMsHeavyGunnerElement;
  };

  interface HTMLMsKnightElement extends Components.MsKnight, HTMLStencilElement {}
  var HTMLMsKnightElement: {
    prototype: HTMLMsKnightElement;
    new (): HTMLMsKnightElement;
  };

  interface HTMLMsPriestElement extends Components.MsPriest, HTMLStencilElement {}
  var HTMLMsPriestElement: {
    prototype: HTMLMsPriestElement;
    new (): HTMLMsPriestElement;
  };

  interface HTMLMsRunebladeElement extends Components.MsRuneblade, HTMLStencilElement {}
  var HTMLMsRunebladeElement: {
    prototype: HTMLMsRunebladeElement;
    new (): HTMLMsRunebladeElement;
  };

  interface HTMLMsSoulBinderElement extends Components.MsSoulBinder, HTMLStencilElement {}
  var HTMLMsSoulBinderElement: {
    prototype: HTMLMsSoulBinderElement;
    new (): HTMLMsSoulBinderElement;
  };

  interface HTMLMsThiefElement extends Components.MsThief, HTMLStencilElement {}
  var HTMLMsThiefElement: {
    prototype: HTMLMsThiefElement;
    new (): HTMLMsThiefElement;
  };

  interface HTMLMsWizardElement extends Components.MsWizard, HTMLStencilElement {}
  var HTMLMsWizardElement: {
    prototype: HTMLMsWizardElement;
    new (): HTMLMsWizardElement;
  };

  interface HTMLMsExtraCounterElement extends Components.MsExtraCounter, HTMLStencilElement {}
  var HTMLMsExtraCounterElement: {
    prototype: HTMLMsExtraCounterElement;
    new (): HTMLMsExtraCounterElement;
  };

  interface HTMLMsExtraOutletElement extends Components.MsExtraOutlet, HTMLStencilElement {}
  var HTMLMsExtraOutletElement: {
    prototype: HTMLMsExtraOutletElement;
    new (): HTMLMsExtraOutletElement;
  };

  interface HTMLMsFooterElement extends Components.MsFooter, HTMLStencilElement {}
  var HTMLMsFooterElement: {
    prototype: HTMLMsFooterElement;
    new (): HTMLMsFooterElement;
  };

  interface HTMLMsIconElement extends Components.MsIcon, HTMLStencilElement {}
  var HTMLMsIconElement: {
    prototype: HTMLMsIconElement;
    new (): HTMLMsIconElement;
  };

  interface HTMLMsSkillOverlayElement extends Components.MsSkillOverlay, HTMLStencilElement {}
  var HTMLMsSkillOverlayElement: {
    prototype: HTMLMsSkillOverlayElement;
    new (): HTMLMsSkillOverlayElement;
  };

  interface HTMLMsSkillElement extends Components.MsSkill, HTMLStencilElement {}
  var HTMLMsSkillElement: {
    prototype: HTMLMsSkillElement;
    new (): HTMLMsSkillElement;
  };

  interface HTMLElementTagNameMap {
    'ms-archer': HTMLMsArcherElement
    'ms-assassin': HTMLMsAssassinElement
    'ms-berserker': HTMLMsBerserkerElement
    'ms-chart': HTMLMsChartElement
    'ms-heavy-gunner': HTMLMsHeavyGunnerElement
    'ms-knight': HTMLMsKnightElement
    'ms-priest': HTMLMsPriestElement
    'ms-runeblade': HTMLMsRunebladeElement
    'ms-soul-binder': HTMLMsSoulBinderElement
    'ms-thief': HTMLMsThiefElement
    'ms-wizard': HTMLMsWizardElement
    'ms-extra-counter': HTMLMsExtraCounterElement
    'ms-extra-outlet': HTMLMsExtraOutletElement
    'ms-footer': HTMLMsFooterElement
    'ms-icon': HTMLMsIconElement
    'ms-skill-overlay': HTMLMsSkillOverlayElement
    'ms-skill': HTMLMsSkillElement
  }

  interface ElementTagNameMap {
    'ms-archer': HTMLMsArcherElement;
    'ms-assassin': HTMLMsAssassinElement;
    'ms-berserker': HTMLMsBerserkerElement;
    'ms-chart': HTMLMsChartElement;
    'ms-heavy-gunner': HTMLMsHeavyGunnerElement;
    'ms-knight': HTMLMsKnightElement;
    'ms-priest': HTMLMsPriestElement;
    'ms-runeblade': HTMLMsRunebladeElement;
    'ms-soul-binder': HTMLMsSoulBinderElement;
    'ms-thief': HTMLMsThiefElement;
    'ms-wizard': HTMLMsWizardElement;
    'ms-extra-counter': HTMLMsExtraCounterElement;
    'ms-extra-outlet': HTMLMsExtraOutletElement;
    'ms-footer': HTMLMsFooterElement;
    'ms-icon': HTMLMsIconElement;
    'ms-skill-overlay': HTMLMsSkillOverlayElement;
    'ms-skill': HTMLMsSkillElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
