/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  MapleStoryClass,
} from './components/editor/editor.interfaces';


export namespace Components {

  interface MsArcher {
    'agileArcher': number;
    'arrowBarrage': number;
    'arrowStorm': number;
    'arrowStream': number;
    'bowSwing': number;
    'bronzeEagle': number;
    'conditioning': number;
    'eagleClaw': number;
    'eagleGlide': number;
    'eaglesMajesty': number;
    'evasiveSalvo': number;
    'iceArrow': number;
    'precisionShooter': number;
    'rapidShot': number;
    'screwdriverShot': number;
    'sharpEyes': number;
    'snipe': number;
  }
  interface MsArcherAttributes extends StencilHTMLAttributes {
    'agileArcher'?: number;
    'arrowBarrage'?: number;
    'arrowStorm'?: number;
    'arrowStream'?: number;
    'bowSwing'?: number;
    'bronzeEagle'?: number;
    'conditioning'?: number;
    'eagleClaw'?: number;
    'eagleGlide'?: number;
    'eaglesMajesty'?: number;
    'evasiveSalvo'?: number;
    'iceArrow'?: number;
    'precisionShooter'?: number;
    'rapidShot'?: number;
    'screwdriverShot'?: number;
    'sharpEyes'?: number;
    'snipe'?: number;
  }

  interface MsAssassin {
    'darkCloak': number;
    'dash': number;
    'deathSentence': number;
    'fatalStrikes': number;
    'fragmentedStar': number;
    'luckyStars': number;
    'markOfDeath': number;
    'mirrorImageDarkBlade': number;
    'shadowArts': number;
    'shadowBurst': number;
    'shadowChaser': number;
    'shadowCutter': number;
    'shadowWeb': number;
    'soulGrind': number;
    'starChaser': number;
    'starFlurry': number;
    'thrownWeaponMastery': number;
  }
  interface MsAssassinAttributes extends StencilHTMLAttributes {
    'darkCloak'?: number;
    'dash'?: number;
    'deathSentence'?: number;
    'fatalStrikes'?: number;
    'fragmentedStar'?: number;
    'luckyStars'?: number;
    'markOfDeath'?: number;
    'mirrorImageDarkBlade'?: number;
    'shadowArts'?: number;
    'shadowBurst'?: number;
    'shadowChaser'?: number;
    'shadowCutter'?: number;
    'shadowWeb'?: number;
    'soulGrind'?: number;
    'starChaser'?: number;
    'starFlurry'?: number;
    'thrownWeaponMastery'?: number;
  }

  interface MsPriest {
    'angelicRay': number;
    'celestialBlessings': number;
    'celestialGuardian': number;
    'celestialLight': number;
    'disciple': number;
    'healingMastery': number;
    'healingPrayer': number;
    'heavenlyWings': number;
    'holyBlast': number;
    'holyRelic': number;
    'holySymbol': number;
    'sanctuary': number;
    'scepterMastery': number;
    'scourgingWave': number;
    'shieldOfTheArchon': number;
    'smitingAura': number;
    'steadfastFaith': number;
  }
  interface MsPriestAttributes extends StencilHTMLAttributes {
    'angelicRay'?: number;
    'celestialBlessings'?: number;
    'celestialGuardian'?: number;
    'celestialLight'?: number;
    'disciple'?: number;
    'healingMastery'?: number;
    'healingPrayer'?: number;
    'heavenlyWings'?: number;
    'holyBlast'?: number;
    'holyRelic'?: number;
    'holySymbol'?: number;
    'sanctuary'?: number;
    'scepterMastery'?: number;
    'scourgingWave'?: number;
    'shieldOfTheArchon'?: number;
    'smitingAura'?: number;
    'steadfastFaith'?: number;
  }

  interface MsRuneblade {
    'bladeChasm': number;
    'bladeMastery': number;
    'blink': number;
    'echoingBlade': number;
    'elementalPotency': number;
    'flameSigil': number;
    'flurry': number;
    'frostSigil': number;
    'gravityRune': number;
    'honingRunes': number;
    'illusoryBlades': number;
    'impact': number;
    'runeBalance': number;
    'runeFocus': number;
    'stormSigil': number;
    'wardingRune': number;
    'whirlingBlades': number;
  }
  interface MsRunebladeAttributes extends StencilHTMLAttributes {
    'bladeChasm'?: number;
    'bladeMastery'?: number;
    'blink'?: number;
    'echoingBlade'?: number;
    'elementalPotency'?: number;
    'flameSigil'?: number;
    'flurry'?: number;
    'frostSigil'?: number;
    'gravityRune'?: number;
    'honingRunes'?: number;
    'illusoryBlades'?: number;
    'impact'?: number;
    'runeBalance'?: number;
    'runeFocus'?: number;
    'stormSigil'?: number;
    'wardingRune'?: number;
    'whirlingBlades'?: number;
  }

  interface MsWizard {
    'arcaneBlast': number;
    'chainLightning': number;
    'cryomancy': number;
    'electromancy': number;
    'elementalMaster': number;
    'flameTornado': number;
    'flameWave': number;
    'focusSeal': number;
    'iceSpear': number;
    'iceStorm': number;
    'magicArmor': number;
    'manaClaw': number;
    'manaFont': number;
    'phantomClaw': number;
    'pyromancy': number;
    'teleport': number;
    'thunderbolt': number;
  }
  interface MsWizardAttributes extends StencilHTMLAttributes {
    'arcaneBlast'?: number;
    'chainLightning'?: number;
    'cryomancy'?: number;
    'electromancy'?: number;
    'elementalMaster'?: number;
    'flameTornado'?: number;
    'flameWave'?: number;
    'focusSeal'?: number;
    'iceSpear'?: number;
    'iceStorm'?: number;
    'magicArmor'?: number;
    'manaClaw'?: number;
    'manaFont'?: number;
    'phantomClaw'?: number;
    'pyromancy'?: number;
    'teleport'?: number;
    'thunderbolt'?: number;
  }

  interface MsArcherEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsArcherEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsAssassinEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsAssassinEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsPriestEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsPriestEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsRunebladeEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsRunebladeEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsWizardEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsWizardEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsEditorOutlet {
    'editor': string;
  }
  interface MsEditorOutletAttributes extends StencilHTMLAttributes {
    'editor'?: string;
  }

  interface MsEditor {
    'msClass': MapleStoryClass;
    'toHtmlString': () => Promise<string>;
  }
  interface MsEditorAttributes extends StencilHTMLAttributes {
    'msClass'?: MapleStoryClass;
    'onChanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsLevelControl {
    'level': number;
    'max': number;
    'min': number;
  }
  interface MsLevelControlAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
    'min'?: number;
    'onLevelchanged'?: (event: CustomEvent<number>) => void;
  }

  interface MsIcon {
    'name': string;
  }
  interface MsIconAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface MsSkillOverlay {
    'cooldown': number;
    'element': string;
    'heading': string;
    'level': number;
    'max': number;
    'passive': boolean;
    'requirements': string[];
    'spirit': number;
    'type': string;
    'weaponRequired': string;
  }
  interface MsSkillOverlayAttributes extends StencilHTMLAttributes {
    'cooldown'?: number;
    'element'?: string;
    'heading'?: string;
    'level'?: number;
    'max'?: number;
    'passive'?: boolean;
    'requirements'?: string[];
    'spirit'?: number;
    'type'?: string;
    'weaponRequired'?: string;
  }

  interface MsAgileArcher {
    'level': number;
    'max': number;
  }
  interface MsAgileArcherAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowBarrage {
    'level': number;
    'max': number;
  }
  interface MsArrowBarrageAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowStorm {
    'level': number;
    'max': number;
  }
  interface MsArrowStormAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowStream {
    'level': number;
    'max': number;
  }
  interface MsArrowStreamAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBowSwing {
    'level': number;
    'max': number;
  }
  interface MsBowSwingAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBronzeEagle {
    'level': number;
    'max': number;
  }
  interface MsBronzeEagleAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsConditioning {
    'level': number;
    'max': number;
  }
  interface MsConditioningAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEagleClaw {
    'level': number;
    'max': number;
  }
  interface MsEagleClawAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEagleGlide {
    'level': number;
    'max': number;
  }
  interface MsEagleGlideAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEaglesMajesty {
    'level': number;
    'max': number;
  }
  interface MsEaglesMajestyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEvasiveSalvo {
    'level': number;
    'max': number;
  }
  interface MsEvasiveSalvoAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsIceArrow {
    'level': number;
    'max': number;
  }
  interface MsIceArrowAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsPrecisionShooter {
    'level': number;
    'max': number;
  }
  interface MsPrecisionShooterAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsRapidShot {
    'level': number;
    'max': number;
  }
  interface MsRapidShotAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScrewdriverShot {
    'level': number;
    'max': number;
  }
  interface MsScrewdriverShotAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSharpEyes {
    'level': number;
    'max': number;
  }
  interface MsSharpEyesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSnipe {
    'level': number;
    'max': number;
  }
  interface MsSnipeAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsDarkCloak {
    'level': number;
    'max': number;
  }
  interface MsDarkCloakAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsDash {
    'level': number;
    'max': number;
  }
  interface MsDashAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsDeathSentence {
    'level': number;
    'max': number;
  }
  interface MsDeathSentenceAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFatalStrikes {
    'level': number;
    'max': number;
  }
  interface MsFatalStrikesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFragmentedStar {
    'level': number;
    'max': number;
  }
  interface MsFragmentedStarAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsLuckyStars {
    'level': number;
    'max': number;
  }
  interface MsLuckyStarsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsMarkOfDeath {
    'level': number;
    'max': number;
  }
  interface MsMarkOfDeathAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsMirrorImageDarkBlade {
    'level': number;
    'max': number;
  }
  interface MsMirrorImageDarkBladeAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShadowArts {
    'level': number;
    'max': number;
  }
  interface MsShadowArtsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShadowBurst {
    'level': number;
    'max': number;
  }
  interface MsShadowBurstAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShadowChaser {
    'level': number;
    'max': number;
  }
  interface MsShadowChaserAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShadowCutter {
    'level': number;
    'max': number;
  }
  interface MsShadowCutterAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShadowWeb {
    'level': number;
    'max': number;
  }
  interface MsShadowWebAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSoulGrind {
    'level': number;
    'max': number;
  }
  interface MsSoulGrindAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsStarChaser {
    'level': number;
    'max': number;
  }
  interface MsStarChaserAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsStarFlurry {
    'level': number;
    'max': number;
  }
  interface MsStarFlurryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsThrownWeaponMastery {
    'level': number;
    'max': number;
  }
  interface MsThrownWeaponMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsAngelicRay {
    'level': number;
    'max': number;
  }
  interface MsAngelicRayAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialBlessings {
    'level': number;
    'max': number;
  }
  interface MsCelestialBlessingsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialGuardian {
    'level': number;
    'max': number;
  }
  interface MsCelestialGuardianAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialLight {
    'level': number;
    'max': number;
  }
  interface MsCelestialLightAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsDisciple {
    'level': number;
    'max': number;
  }
  interface MsDiscipleAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHealingMastery {
    'level': number;
    'max': number;
  }
  interface MsHealingMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHealingPrayer {
    'level': number;
    'max': number;
  }
  interface MsHealingPrayerAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHeavenlyWings {
    'level': number;
    'max': number;
  }
  interface MsHeavenlyWingsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolyBlast {
    'level': number;
    'max': number;
  }
  interface MsHolyBlastAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolyRelic {
    'level': number;
    'max': number;
  }
  interface MsHolyRelicAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolySymbol {
    'level': number;
    'max': number;
  }
  interface MsHolySymbolAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSanctuary {
    'level': number;
    'max': number;
  }
  interface MsSanctuaryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScepterMastery {
    'level': number;
    'max': number;
  }
  interface MsScepterMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScourgingWave {
    'level': number;
    'max': number;
  }
  interface MsScourgingWaveAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShieldOfTheArchon {
    'level': number;
    'max': number;
  }
  interface MsShieldOfTheArchonAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSmitingAura {
    'level': number;
    'max': number;
  }
  interface MsSmitingAuraAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSteadfastFaith {
    'level': number;
    'max': number;
  }
  interface MsSteadfastFaithAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBladeChasm {
    'level': number;
    'max': number;
  }
  interface MsBladeChasmAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBladeMastery {
    'level': number;
    'max': number;
  }
  interface MsBladeMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBlink {
    'level': number;
    'max': number;
  }
  interface MsBlinkAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEchoingBlade {
    'level': number;
    'max': number;
  }
  interface MsEchoingBladeAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsElementalPotency {
    'level': number;
    'max': number;
  }
  interface MsElementalPotencyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFlameSigil {
    'level': number;
    'max': number;
  }
  interface MsFlameSigilAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFlurry {
    'level': number;
    'max': number;
  }
  interface MsFlurryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFrostSigil {
    'level': number;
    'max': number;
  }
  interface MsFrostSigilAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsGravityRune {
    'level': number;
    'max': number;
  }
  interface MsGravityRuneAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHoningRunes {
    'level': number;
    'max': number;
  }
  interface MsHoningRunesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsIllusoryBlades {
    'level': number;
    'max': number;
  }
  interface MsIllusoryBladesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsImpact {
    'level': number;
    'max': number;
  }
  interface MsImpactAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsRuneBalance {
    'level': number;
    'max': number;
  }
  interface MsRuneBalanceAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsRuneFocus {
    'level': number;
    'max': number;
  }
  interface MsRuneFocusAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsStormSigil {
    'level': number;
    'max': number;
  }
  interface MsStormSigilAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsWardingRune {
    'level': number;
    'max': number;
  }
  interface MsWardingRuneAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsWhirlingBlades {
    'level': number;
    'max': number;
  }
  interface MsWhirlingBladesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArcaneBlast {
    'level': number;
    'max': number;
  }
  interface MsArcaneBlastAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsChainLightning {
    'level': number;
    'max': number;
  }
  interface MsChainLightningAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCryomancy {
    'level': number;
    'max': number;
  }
  interface MsCryomancyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsElectromancy {
    'level': number;
    'max': number;
  }
  interface MsElectromancyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsElementalMaster {
    'level': number;
    'max': number;
  }
  interface MsElementalMasterAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFlameTornado {
    'level': number;
    'max': number;
  }
  interface MsFlameTornadoAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFlameWave {
    'level': number;
    'max': number;
  }
  interface MsFlameWaveAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsFocusSeal {
    'level': number;
    'max': number;
  }
  interface MsFocusSealAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsIceSpear {
    'level': number;
    'max': number;
  }
  interface MsIceSpearAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsIceStorm {
    'level': number;
    'max': number;
  }
  interface MsIceStormAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsMagicArmor {
    'level': number;
    'max': number;
  }
  interface MsMagicArmorAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsManaClaw {
    'level': number;
    'max': number;
  }
  interface MsManaClawAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsManaFont {
    'level': number;
    'max': number;
  }
  interface MsManaFontAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsPhantomClaw {
    'level': number;
    'max': number;
  }
  interface MsPhantomClawAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsPyromancy {
    'level': number;
    'max': number;
  }
  interface MsPyromancyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsTeleport {
    'level': number;
    'max': number;
  }
  interface MsTeleportAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsThunderbolt {
    'level': number;
    'max': number;
  }
  interface MsThunderboltAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MsArcher': Components.MsArcher;
    'MsAssassin': Components.MsAssassin;
    'MsPriest': Components.MsPriest;
    'MsRuneblade': Components.MsRuneblade;
    'MsWizard': Components.MsWizard;
    'MsArcherEditor': Components.MsArcherEditor;
    'MsAssassinEditor': Components.MsAssassinEditor;
    'MsPriestEditor': Components.MsPriestEditor;
    'MsRunebladeEditor': Components.MsRunebladeEditor;
    'MsWizardEditor': Components.MsWizardEditor;
    'MsEditorOutlet': Components.MsEditorOutlet;
    'MsEditor': Components.MsEditor;
    'MsLevelControl': Components.MsLevelControl;
    'MsIcon': Components.MsIcon;
    'MsSkillOverlay': Components.MsSkillOverlay;
    'MsAgileArcher': Components.MsAgileArcher;
    'MsArrowBarrage': Components.MsArrowBarrage;
    'MsArrowStorm': Components.MsArrowStorm;
    'MsArrowStream': Components.MsArrowStream;
    'MsBowSwing': Components.MsBowSwing;
    'MsBronzeEagle': Components.MsBronzeEagle;
    'MsConditioning': Components.MsConditioning;
    'MsEagleClaw': Components.MsEagleClaw;
    'MsEagleGlide': Components.MsEagleGlide;
    'MsEaglesMajesty': Components.MsEaglesMajesty;
    'MsEvasiveSalvo': Components.MsEvasiveSalvo;
    'MsIceArrow': Components.MsIceArrow;
    'MsPrecisionShooter': Components.MsPrecisionShooter;
    'MsRapidShot': Components.MsRapidShot;
    'MsScrewdriverShot': Components.MsScrewdriverShot;
    'MsSharpEyes': Components.MsSharpEyes;
    'MsSnipe': Components.MsSnipe;
    'MsDarkCloak': Components.MsDarkCloak;
    'MsDash': Components.MsDash;
    'MsDeathSentence': Components.MsDeathSentence;
    'MsFatalStrikes': Components.MsFatalStrikes;
    'MsFragmentedStar': Components.MsFragmentedStar;
    'MsLuckyStars': Components.MsLuckyStars;
    'MsMarkOfDeath': Components.MsMarkOfDeath;
    'MsMirrorImageDarkBlade': Components.MsMirrorImageDarkBlade;
    'MsShadowArts': Components.MsShadowArts;
    'MsShadowBurst': Components.MsShadowBurst;
    'MsShadowChaser': Components.MsShadowChaser;
    'MsShadowCutter': Components.MsShadowCutter;
    'MsShadowWeb': Components.MsShadowWeb;
    'MsSoulGrind': Components.MsSoulGrind;
    'MsStarChaser': Components.MsStarChaser;
    'MsStarFlurry': Components.MsStarFlurry;
    'MsThrownWeaponMastery': Components.MsThrownWeaponMastery;
    'MsAngelicRay': Components.MsAngelicRay;
    'MsCelestialBlessings': Components.MsCelestialBlessings;
    'MsCelestialGuardian': Components.MsCelestialGuardian;
    'MsCelestialLight': Components.MsCelestialLight;
    'MsDisciple': Components.MsDisciple;
    'MsHealingMastery': Components.MsHealingMastery;
    'MsHealingPrayer': Components.MsHealingPrayer;
    'MsHeavenlyWings': Components.MsHeavenlyWings;
    'MsHolyBlast': Components.MsHolyBlast;
    'MsHolyRelic': Components.MsHolyRelic;
    'MsHolySymbol': Components.MsHolySymbol;
    'MsSanctuary': Components.MsSanctuary;
    'MsScepterMastery': Components.MsScepterMastery;
    'MsScourgingWave': Components.MsScourgingWave;
    'MsShieldOfTheArchon': Components.MsShieldOfTheArchon;
    'MsSmitingAura': Components.MsSmitingAura;
    'MsSteadfastFaith': Components.MsSteadfastFaith;
    'MsBladeChasm': Components.MsBladeChasm;
    'MsBladeMastery': Components.MsBladeMastery;
    'MsBlink': Components.MsBlink;
    'MsEchoingBlade': Components.MsEchoingBlade;
    'MsElementalPotency': Components.MsElementalPotency;
    'MsFlameSigil': Components.MsFlameSigil;
    'MsFlurry': Components.MsFlurry;
    'MsFrostSigil': Components.MsFrostSigil;
    'MsGravityRune': Components.MsGravityRune;
    'MsHoningRunes': Components.MsHoningRunes;
    'MsIllusoryBlades': Components.MsIllusoryBlades;
    'MsImpact': Components.MsImpact;
    'MsRuneBalance': Components.MsRuneBalance;
    'MsRuneFocus': Components.MsRuneFocus;
    'MsStormSigil': Components.MsStormSigil;
    'MsWardingRune': Components.MsWardingRune;
    'MsWhirlingBlades': Components.MsWhirlingBlades;
    'MsArcaneBlast': Components.MsArcaneBlast;
    'MsChainLightning': Components.MsChainLightning;
    'MsCryomancy': Components.MsCryomancy;
    'MsElectromancy': Components.MsElectromancy;
    'MsElementalMaster': Components.MsElementalMaster;
    'MsFlameTornado': Components.MsFlameTornado;
    'MsFlameWave': Components.MsFlameWave;
    'MsFocusSeal': Components.MsFocusSeal;
    'MsIceSpear': Components.MsIceSpear;
    'MsIceStorm': Components.MsIceStorm;
    'MsMagicArmor': Components.MsMagicArmor;
    'MsManaClaw': Components.MsManaClaw;
    'MsManaFont': Components.MsManaFont;
    'MsPhantomClaw': Components.MsPhantomClaw;
    'MsPyromancy': Components.MsPyromancy;
    'MsTeleport': Components.MsTeleport;
    'MsThunderbolt': Components.MsThunderbolt;
  }

  interface StencilIntrinsicElements {
    'ms-archer': Components.MsArcherAttributes;
    'ms-assassin': Components.MsAssassinAttributes;
    'ms-priest': Components.MsPriestAttributes;
    'ms-runeblade': Components.MsRunebladeAttributes;
    'ms-wizard': Components.MsWizardAttributes;
    'ms-archer-editor': Components.MsArcherEditorAttributes;
    'ms-assassin-editor': Components.MsAssassinEditorAttributes;
    'ms-priest-editor': Components.MsPriestEditorAttributes;
    'ms-runeblade-editor': Components.MsRunebladeEditorAttributes;
    'ms-wizard-editor': Components.MsWizardEditorAttributes;
    'ms-editor-outlet': Components.MsEditorOutletAttributes;
    'ms-editor': Components.MsEditorAttributes;
    'ms-level-control': Components.MsLevelControlAttributes;
    'ms-icon': Components.MsIconAttributes;
    'ms-skill-overlay': Components.MsSkillOverlayAttributes;
    'ms-agile-archer': Components.MsAgileArcherAttributes;
    'ms-arrow-barrage': Components.MsArrowBarrageAttributes;
    'ms-arrow-storm': Components.MsArrowStormAttributes;
    'ms-arrow-stream': Components.MsArrowStreamAttributes;
    'ms-bow-swing': Components.MsBowSwingAttributes;
    'ms-bronze-eagle': Components.MsBronzeEagleAttributes;
    'ms-conditioning': Components.MsConditioningAttributes;
    'ms-eagle-claw': Components.MsEagleClawAttributes;
    'ms-eagle-glide': Components.MsEagleGlideAttributes;
    'ms-eagles-majesty': Components.MsEaglesMajestyAttributes;
    'ms-evasive-salvo': Components.MsEvasiveSalvoAttributes;
    'ms-ice-arrow': Components.MsIceArrowAttributes;
    'ms-precision-shooter': Components.MsPrecisionShooterAttributes;
    'ms-rapid-shot': Components.MsRapidShotAttributes;
    'ms-screwdriver-shot': Components.MsScrewdriverShotAttributes;
    'ms-sharp-eyes': Components.MsSharpEyesAttributes;
    'ms-snipe': Components.MsSnipeAttributes;
    'ms-dark-cloak': Components.MsDarkCloakAttributes;
    'ms-dash': Components.MsDashAttributes;
    'ms-death-sentence': Components.MsDeathSentenceAttributes;
    'ms-fatal-strikes': Components.MsFatalStrikesAttributes;
    'ms-fragmented-star': Components.MsFragmentedStarAttributes;
    'ms-lucky-stars': Components.MsLuckyStarsAttributes;
    'ms-mark-of-death': Components.MsMarkOfDeathAttributes;
    'ms-mirror-image-dark-blade': Components.MsMirrorImageDarkBladeAttributes;
    'ms-shadow-arts': Components.MsShadowArtsAttributes;
    'ms-shadow-burst': Components.MsShadowBurstAttributes;
    'ms-shadow-chaser': Components.MsShadowChaserAttributes;
    'ms-shadow-cutter': Components.MsShadowCutterAttributes;
    'ms-shadow-web': Components.MsShadowWebAttributes;
    'ms-soul-grind': Components.MsSoulGrindAttributes;
    'ms-star-chaser': Components.MsStarChaserAttributes;
    'ms-star-flurry': Components.MsStarFlurryAttributes;
    'ms-thrown-weapon-mastery': Components.MsThrownWeaponMasteryAttributes;
    'ms-angelic-ray': Components.MsAngelicRayAttributes;
    'ms-celestial-blessings': Components.MsCelestialBlessingsAttributes;
    'ms-celestial-guardian': Components.MsCelestialGuardianAttributes;
    'ms-celestial-light': Components.MsCelestialLightAttributes;
    'ms-disciple': Components.MsDiscipleAttributes;
    'ms-healing-mastery': Components.MsHealingMasteryAttributes;
    'ms-healing-prayer': Components.MsHealingPrayerAttributes;
    'ms-heavenly-wings': Components.MsHeavenlyWingsAttributes;
    'ms-holy-blast': Components.MsHolyBlastAttributes;
    'ms-holy-relic': Components.MsHolyRelicAttributes;
    'ms-holy-symbol': Components.MsHolySymbolAttributes;
    'ms-sanctuary': Components.MsSanctuaryAttributes;
    'ms-scepter-mastery': Components.MsScepterMasteryAttributes;
    'ms-scourging-wave': Components.MsScourgingWaveAttributes;
    'ms-shield-of-the-archon': Components.MsShieldOfTheArchonAttributes;
    'ms-smiting-aura': Components.MsSmitingAuraAttributes;
    'ms-steadfast-faith': Components.MsSteadfastFaithAttributes;
    'ms-blade-chasm': Components.MsBladeChasmAttributes;
    'ms-blade-mastery': Components.MsBladeMasteryAttributes;
    'ms-blink': Components.MsBlinkAttributes;
    'ms-echoing-blade': Components.MsEchoingBladeAttributes;
    'ms-elemental-potency': Components.MsElementalPotencyAttributes;
    'ms-flame-sigil': Components.MsFlameSigilAttributes;
    'ms-flurry': Components.MsFlurryAttributes;
    'ms-frost-sigil': Components.MsFrostSigilAttributes;
    'ms-gravity-rune': Components.MsGravityRuneAttributes;
    'ms-honing-runes': Components.MsHoningRunesAttributes;
    'ms-illusory-blades': Components.MsIllusoryBladesAttributes;
    'ms-impact': Components.MsImpactAttributes;
    'ms-rune-balance': Components.MsRuneBalanceAttributes;
    'ms-rune-focus': Components.MsRuneFocusAttributes;
    'ms-storm-sigil': Components.MsStormSigilAttributes;
    'ms-warding-rune': Components.MsWardingRuneAttributes;
    'ms-whirling-blades': Components.MsWhirlingBladesAttributes;
    'ms-arcane-blast': Components.MsArcaneBlastAttributes;
    'ms-chain-lightning': Components.MsChainLightningAttributes;
    'ms-cryomancy': Components.MsCryomancyAttributes;
    'ms-electromancy': Components.MsElectromancyAttributes;
    'ms-elemental-master': Components.MsElementalMasterAttributes;
    'ms-flame-tornado': Components.MsFlameTornadoAttributes;
    'ms-flame-wave': Components.MsFlameWaveAttributes;
    'ms-focus-seal': Components.MsFocusSealAttributes;
    'ms-ice-spear': Components.MsIceSpearAttributes;
    'ms-ice-storm': Components.MsIceStormAttributes;
    'ms-magic-armor': Components.MsMagicArmorAttributes;
    'ms-mana-claw': Components.MsManaClawAttributes;
    'ms-mana-font': Components.MsManaFontAttributes;
    'ms-phantom-claw': Components.MsPhantomClawAttributes;
    'ms-pyromancy': Components.MsPyromancyAttributes;
    'ms-teleport': Components.MsTeleportAttributes;
    'ms-thunderbolt': Components.MsThunderboltAttributes;
  }


  interface HTMLMsArcherElement extends Components.MsArcher, HTMLStencilElement {}
  var HTMLMsArcherElement: {
    prototype: HTMLMsArcherElement;
    new (): HTMLMsArcherElement;
  };

  interface HTMLMsAssassinElement extends Components.MsAssassin, HTMLStencilElement {}
  var HTMLMsAssassinElement: {
    prototype: HTMLMsAssassinElement;
    new (): HTMLMsAssassinElement;
  };

  interface HTMLMsPriestElement extends Components.MsPriest, HTMLStencilElement {}
  var HTMLMsPriestElement: {
    prototype: HTMLMsPriestElement;
    new (): HTMLMsPriestElement;
  };

  interface HTMLMsRunebladeElement extends Components.MsRuneblade, HTMLStencilElement {}
  var HTMLMsRunebladeElement: {
    prototype: HTMLMsRunebladeElement;
    new (): HTMLMsRunebladeElement;
  };

  interface HTMLMsWizardElement extends Components.MsWizard, HTMLStencilElement {}
  var HTMLMsWizardElement: {
    prototype: HTMLMsWizardElement;
    new (): HTMLMsWizardElement;
  };

  interface HTMLMsArcherEditorElement extends Components.MsArcherEditor, HTMLStencilElement {}
  var HTMLMsArcherEditorElement: {
    prototype: HTMLMsArcherEditorElement;
    new (): HTMLMsArcherEditorElement;
  };

  interface HTMLMsAssassinEditorElement extends Components.MsAssassinEditor, HTMLStencilElement {}
  var HTMLMsAssassinEditorElement: {
    prototype: HTMLMsAssassinEditorElement;
    new (): HTMLMsAssassinEditorElement;
  };

  interface HTMLMsPriestEditorElement extends Components.MsPriestEditor, HTMLStencilElement {}
  var HTMLMsPriestEditorElement: {
    prototype: HTMLMsPriestEditorElement;
    new (): HTMLMsPriestEditorElement;
  };

  interface HTMLMsRunebladeEditorElement extends Components.MsRunebladeEditor, HTMLStencilElement {}
  var HTMLMsRunebladeEditorElement: {
    prototype: HTMLMsRunebladeEditorElement;
    new (): HTMLMsRunebladeEditorElement;
  };

  interface HTMLMsWizardEditorElement extends Components.MsWizardEditor, HTMLStencilElement {}
  var HTMLMsWizardEditorElement: {
    prototype: HTMLMsWizardEditorElement;
    new (): HTMLMsWizardEditorElement;
  };

  interface HTMLMsEditorOutletElement extends Components.MsEditorOutlet, HTMLStencilElement {}
  var HTMLMsEditorOutletElement: {
    prototype: HTMLMsEditorOutletElement;
    new (): HTMLMsEditorOutletElement;
  };

  interface HTMLMsEditorElement extends Components.MsEditor, HTMLStencilElement {}
  var HTMLMsEditorElement: {
    prototype: HTMLMsEditorElement;
    new (): HTMLMsEditorElement;
  };

  interface HTMLMsLevelControlElement extends Components.MsLevelControl, HTMLStencilElement {}
  var HTMLMsLevelControlElement: {
    prototype: HTMLMsLevelControlElement;
    new (): HTMLMsLevelControlElement;
  };

  interface HTMLMsIconElement extends Components.MsIcon, HTMLStencilElement {}
  var HTMLMsIconElement: {
    prototype: HTMLMsIconElement;
    new (): HTMLMsIconElement;
  };

  interface HTMLMsSkillOverlayElement extends Components.MsSkillOverlay, HTMLStencilElement {}
  var HTMLMsSkillOverlayElement: {
    prototype: HTMLMsSkillOverlayElement;
    new (): HTMLMsSkillOverlayElement;
  };

  interface HTMLMsAgileArcherElement extends Components.MsAgileArcher, HTMLStencilElement {}
  var HTMLMsAgileArcherElement: {
    prototype: HTMLMsAgileArcherElement;
    new (): HTMLMsAgileArcherElement;
  };

  interface HTMLMsArrowBarrageElement extends Components.MsArrowBarrage, HTMLStencilElement {}
  var HTMLMsArrowBarrageElement: {
    prototype: HTMLMsArrowBarrageElement;
    new (): HTMLMsArrowBarrageElement;
  };

  interface HTMLMsArrowStormElement extends Components.MsArrowStorm, HTMLStencilElement {}
  var HTMLMsArrowStormElement: {
    prototype: HTMLMsArrowStormElement;
    new (): HTMLMsArrowStormElement;
  };

  interface HTMLMsArrowStreamElement extends Components.MsArrowStream, HTMLStencilElement {}
  var HTMLMsArrowStreamElement: {
    prototype: HTMLMsArrowStreamElement;
    new (): HTMLMsArrowStreamElement;
  };

  interface HTMLMsBowSwingElement extends Components.MsBowSwing, HTMLStencilElement {}
  var HTMLMsBowSwingElement: {
    prototype: HTMLMsBowSwingElement;
    new (): HTMLMsBowSwingElement;
  };

  interface HTMLMsBronzeEagleElement extends Components.MsBronzeEagle, HTMLStencilElement {}
  var HTMLMsBronzeEagleElement: {
    prototype: HTMLMsBronzeEagleElement;
    new (): HTMLMsBronzeEagleElement;
  };

  interface HTMLMsConditioningElement extends Components.MsConditioning, HTMLStencilElement {}
  var HTMLMsConditioningElement: {
    prototype: HTMLMsConditioningElement;
    new (): HTMLMsConditioningElement;
  };

  interface HTMLMsEagleClawElement extends Components.MsEagleClaw, HTMLStencilElement {}
  var HTMLMsEagleClawElement: {
    prototype: HTMLMsEagleClawElement;
    new (): HTMLMsEagleClawElement;
  };

  interface HTMLMsEagleGlideElement extends Components.MsEagleGlide, HTMLStencilElement {}
  var HTMLMsEagleGlideElement: {
    prototype: HTMLMsEagleGlideElement;
    new (): HTMLMsEagleGlideElement;
  };

  interface HTMLMsEaglesMajestyElement extends Components.MsEaglesMajesty, HTMLStencilElement {}
  var HTMLMsEaglesMajestyElement: {
    prototype: HTMLMsEaglesMajestyElement;
    new (): HTMLMsEaglesMajestyElement;
  };

  interface HTMLMsEvasiveSalvoElement extends Components.MsEvasiveSalvo, HTMLStencilElement {}
  var HTMLMsEvasiveSalvoElement: {
    prototype: HTMLMsEvasiveSalvoElement;
    new (): HTMLMsEvasiveSalvoElement;
  };

  interface HTMLMsIceArrowElement extends Components.MsIceArrow, HTMLStencilElement {}
  var HTMLMsIceArrowElement: {
    prototype: HTMLMsIceArrowElement;
    new (): HTMLMsIceArrowElement;
  };

  interface HTMLMsPrecisionShooterElement extends Components.MsPrecisionShooter, HTMLStencilElement {}
  var HTMLMsPrecisionShooterElement: {
    prototype: HTMLMsPrecisionShooterElement;
    new (): HTMLMsPrecisionShooterElement;
  };

  interface HTMLMsRapidShotElement extends Components.MsRapidShot, HTMLStencilElement {}
  var HTMLMsRapidShotElement: {
    prototype: HTMLMsRapidShotElement;
    new (): HTMLMsRapidShotElement;
  };

  interface HTMLMsScrewdriverShotElement extends Components.MsScrewdriverShot, HTMLStencilElement {}
  var HTMLMsScrewdriverShotElement: {
    prototype: HTMLMsScrewdriverShotElement;
    new (): HTMLMsScrewdriverShotElement;
  };

  interface HTMLMsSharpEyesElement extends Components.MsSharpEyes, HTMLStencilElement {}
  var HTMLMsSharpEyesElement: {
    prototype: HTMLMsSharpEyesElement;
    new (): HTMLMsSharpEyesElement;
  };

  interface HTMLMsSnipeElement extends Components.MsSnipe, HTMLStencilElement {}
  var HTMLMsSnipeElement: {
    prototype: HTMLMsSnipeElement;
    new (): HTMLMsSnipeElement;
  };

  interface HTMLMsDarkCloakElement extends Components.MsDarkCloak, HTMLStencilElement {}
  var HTMLMsDarkCloakElement: {
    prototype: HTMLMsDarkCloakElement;
    new (): HTMLMsDarkCloakElement;
  };

  interface HTMLMsDashElement extends Components.MsDash, HTMLStencilElement {}
  var HTMLMsDashElement: {
    prototype: HTMLMsDashElement;
    new (): HTMLMsDashElement;
  };

  interface HTMLMsDeathSentenceElement extends Components.MsDeathSentence, HTMLStencilElement {}
  var HTMLMsDeathSentenceElement: {
    prototype: HTMLMsDeathSentenceElement;
    new (): HTMLMsDeathSentenceElement;
  };

  interface HTMLMsFatalStrikesElement extends Components.MsFatalStrikes, HTMLStencilElement {}
  var HTMLMsFatalStrikesElement: {
    prototype: HTMLMsFatalStrikesElement;
    new (): HTMLMsFatalStrikesElement;
  };

  interface HTMLMsFragmentedStarElement extends Components.MsFragmentedStar, HTMLStencilElement {}
  var HTMLMsFragmentedStarElement: {
    prototype: HTMLMsFragmentedStarElement;
    new (): HTMLMsFragmentedStarElement;
  };

  interface HTMLMsLuckyStarsElement extends Components.MsLuckyStars, HTMLStencilElement {}
  var HTMLMsLuckyStarsElement: {
    prototype: HTMLMsLuckyStarsElement;
    new (): HTMLMsLuckyStarsElement;
  };

  interface HTMLMsMarkOfDeathElement extends Components.MsMarkOfDeath, HTMLStencilElement {}
  var HTMLMsMarkOfDeathElement: {
    prototype: HTMLMsMarkOfDeathElement;
    new (): HTMLMsMarkOfDeathElement;
  };

  interface HTMLMsMirrorImageDarkBladeElement extends Components.MsMirrorImageDarkBlade, HTMLStencilElement {}
  var HTMLMsMirrorImageDarkBladeElement: {
    prototype: HTMLMsMirrorImageDarkBladeElement;
    new (): HTMLMsMirrorImageDarkBladeElement;
  };

  interface HTMLMsShadowArtsElement extends Components.MsShadowArts, HTMLStencilElement {}
  var HTMLMsShadowArtsElement: {
    prototype: HTMLMsShadowArtsElement;
    new (): HTMLMsShadowArtsElement;
  };

  interface HTMLMsShadowBurstElement extends Components.MsShadowBurst, HTMLStencilElement {}
  var HTMLMsShadowBurstElement: {
    prototype: HTMLMsShadowBurstElement;
    new (): HTMLMsShadowBurstElement;
  };

  interface HTMLMsShadowChaserElement extends Components.MsShadowChaser, HTMLStencilElement {}
  var HTMLMsShadowChaserElement: {
    prototype: HTMLMsShadowChaserElement;
    new (): HTMLMsShadowChaserElement;
  };

  interface HTMLMsShadowCutterElement extends Components.MsShadowCutter, HTMLStencilElement {}
  var HTMLMsShadowCutterElement: {
    prototype: HTMLMsShadowCutterElement;
    new (): HTMLMsShadowCutterElement;
  };

  interface HTMLMsShadowWebElement extends Components.MsShadowWeb, HTMLStencilElement {}
  var HTMLMsShadowWebElement: {
    prototype: HTMLMsShadowWebElement;
    new (): HTMLMsShadowWebElement;
  };

  interface HTMLMsSoulGrindElement extends Components.MsSoulGrind, HTMLStencilElement {}
  var HTMLMsSoulGrindElement: {
    prototype: HTMLMsSoulGrindElement;
    new (): HTMLMsSoulGrindElement;
  };

  interface HTMLMsStarChaserElement extends Components.MsStarChaser, HTMLStencilElement {}
  var HTMLMsStarChaserElement: {
    prototype: HTMLMsStarChaserElement;
    new (): HTMLMsStarChaserElement;
  };

  interface HTMLMsStarFlurryElement extends Components.MsStarFlurry, HTMLStencilElement {}
  var HTMLMsStarFlurryElement: {
    prototype: HTMLMsStarFlurryElement;
    new (): HTMLMsStarFlurryElement;
  };

  interface HTMLMsThrownWeaponMasteryElement extends Components.MsThrownWeaponMastery, HTMLStencilElement {}
  var HTMLMsThrownWeaponMasteryElement: {
    prototype: HTMLMsThrownWeaponMasteryElement;
    new (): HTMLMsThrownWeaponMasteryElement;
  };

  interface HTMLMsAngelicRayElement extends Components.MsAngelicRay, HTMLStencilElement {}
  var HTMLMsAngelicRayElement: {
    prototype: HTMLMsAngelicRayElement;
    new (): HTMLMsAngelicRayElement;
  };

  interface HTMLMsCelestialBlessingsElement extends Components.MsCelestialBlessings, HTMLStencilElement {}
  var HTMLMsCelestialBlessingsElement: {
    prototype: HTMLMsCelestialBlessingsElement;
    new (): HTMLMsCelestialBlessingsElement;
  };

  interface HTMLMsCelestialGuardianElement extends Components.MsCelestialGuardian, HTMLStencilElement {}
  var HTMLMsCelestialGuardianElement: {
    prototype: HTMLMsCelestialGuardianElement;
    new (): HTMLMsCelestialGuardianElement;
  };

  interface HTMLMsCelestialLightElement extends Components.MsCelestialLight, HTMLStencilElement {}
  var HTMLMsCelestialLightElement: {
    prototype: HTMLMsCelestialLightElement;
    new (): HTMLMsCelestialLightElement;
  };

  interface HTMLMsDiscipleElement extends Components.MsDisciple, HTMLStencilElement {}
  var HTMLMsDiscipleElement: {
    prototype: HTMLMsDiscipleElement;
    new (): HTMLMsDiscipleElement;
  };

  interface HTMLMsHealingMasteryElement extends Components.MsHealingMastery, HTMLStencilElement {}
  var HTMLMsHealingMasteryElement: {
    prototype: HTMLMsHealingMasteryElement;
    new (): HTMLMsHealingMasteryElement;
  };

  interface HTMLMsHealingPrayerElement extends Components.MsHealingPrayer, HTMLStencilElement {}
  var HTMLMsHealingPrayerElement: {
    prototype: HTMLMsHealingPrayerElement;
    new (): HTMLMsHealingPrayerElement;
  };

  interface HTMLMsHeavenlyWingsElement extends Components.MsHeavenlyWings, HTMLStencilElement {}
  var HTMLMsHeavenlyWingsElement: {
    prototype: HTMLMsHeavenlyWingsElement;
    new (): HTMLMsHeavenlyWingsElement;
  };

  interface HTMLMsHolyBlastElement extends Components.MsHolyBlast, HTMLStencilElement {}
  var HTMLMsHolyBlastElement: {
    prototype: HTMLMsHolyBlastElement;
    new (): HTMLMsHolyBlastElement;
  };

  interface HTMLMsHolyRelicElement extends Components.MsHolyRelic, HTMLStencilElement {}
  var HTMLMsHolyRelicElement: {
    prototype: HTMLMsHolyRelicElement;
    new (): HTMLMsHolyRelicElement;
  };

  interface HTMLMsHolySymbolElement extends Components.MsHolySymbol, HTMLStencilElement {}
  var HTMLMsHolySymbolElement: {
    prototype: HTMLMsHolySymbolElement;
    new (): HTMLMsHolySymbolElement;
  };

  interface HTMLMsSanctuaryElement extends Components.MsSanctuary, HTMLStencilElement {}
  var HTMLMsSanctuaryElement: {
    prototype: HTMLMsSanctuaryElement;
    new (): HTMLMsSanctuaryElement;
  };

  interface HTMLMsScepterMasteryElement extends Components.MsScepterMastery, HTMLStencilElement {}
  var HTMLMsScepterMasteryElement: {
    prototype: HTMLMsScepterMasteryElement;
    new (): HTMLMsScepterMasteryElement;
  };

  interface HTMLMsScourgingWaveElement extends Components.MsScourgingWave, HTMLStencilElement {}
  var HTMLMsScourgingWaveElement: {
    prototype: HTMLMsScourgingWaveElement;
    new (): HTMLMsScourgingWaveElement;
  };

  interface HTMLMsShieldOfTheArchonElement extends Components.MsShieldOfTheArchon, HTMLStencilElement {}
  var HTMLMsShieldOfTheArchonElement: {
    prototype: HTMLMsShieldOfTheArchonElement;
    new (): HTMLMsShieldOfTheArchonElement;
  };

  interface HTMLMsSmitingAuraElement extends Components.MsSmitingAura, HTMLStencilElement {}
  var HTMLMsSmitingAuraElement: {
    prototype: HTMLMsSmitingAuraElement;
    new (): HTMLMsSmitingAuraElement;
  };

  interface HTMLMsSteadfastFaithElement extends Components.MsSteadfastFaith, HTMLStencilElement {}
  var HTMLMsSteadfastFaithElement: {
    prototype: HTMLMsSteadfastFaithElement;
    new (): HTMLMsSteadfastFaithElement;
  };

  interface HTMLMsBladeChasmElement extends Components.MsBladeChasm, HTMLStencilElement {}
  var HTMLMsBladeChasmElement: {
    prototype: HTMLMsBladeChasmElement;
    new (): HTMLMsBladeChasmElement;
  };

  interface HTMLMsBladeMasteryElement extends Components.MsBladeMastery, HTMLStencilElement {}
  var HTMLMsBladeMasteryElement: {
    prototype: HTMLMsBladeMasteryElement;
    new (): HTMLMsBladeMasteryElement;
  };

  interface HTMLMsBlinkElement extends Components.MsBlink, HTMLStencilElement {}
  var HTMLMsBlinkElement: {
    prototype: HTMLMsBlinkElement;
    new (): HTMLMsBlinkElement;
  };

  interface HTMLMsEchoingBladeElement extends Components.MsEchoingBlade, HTMLStencilElement {}
  var HTMLMsEchoingBladeElement: {
    prototype: HTMLMsEchoingBladeElement;
    new (): HTMLMsEchoingBladeElement;
  };

  interface HTMLMsElementalPotencyElement extends Components.MsElementalPotency, HTMLStencilElement {}
  var HTMLMsElementalPotencyElement: {
    prototype: HTMLMsElementalPotencyElement;
    new (): HTMLMsElementalPotencyElement;
  };

  interface HTMLMsFlameSigilElement extends Components.MsFlameSigil, HTMLStencilElement {}
  var HTMLMsFlameSigilElement: {
    prototype: HTMLMsFlameSigilElement;
    new (): HTMLMsFlameSigilElement;
  };

  interface HTMLMsFlurryElement extends Components.MsFlurry, HTMLStencilElement {}
  var HTMLMsFlurryElement: {
    prototype: HTMLMsFlurryElement;
    new (): HTMLMsFlurryElement;
  };

  interface HTMLMsFrostSigilElement extends Components.MsFrostSigil, HTMLStencilElement {}
  var HTMLMsFrostSigilElement: {
    prototype: HTMLMsFrostSigilElement;
    new (): HTMLMsFrostSigilElement;
  };

  interface HTMLMsGravityRuneElement extends Components.MsGravityRune, HTMLStencilElement {}
  var HTMLMsGravityRuneElement: {
    prototype: HTMLMsGravityRuneElement;
    new (): HTMLMsGravityRuneElement;
  };

  interface HTMLMsHoningRunesElement extends Components.MsHoningRunes, HTMLStencilElement {}
  var HTMLMsHoningRunesElement: {
    prototype: HTMLMsHoningRunesElement;
    new (): HTMLMsHoningRunesElement;
  };

  interface HTMLMsIllusoryBladesElement extends Components.MsIllusoryBlades, HTMLStencilElement {}
  var HTMLMsIllusoryBladesElement: {
    prototype: HTMLMsIllusoryBladesElement;
    new (): HTMLMsIllusoryBladesElement;
  };

  interface HTMLMsImpactElement extends Components.MsImpact, HTMLStencilElement {}
  var HTMLMsImpactElement: {
    prototype: HTMLMsImpactElement;
    new (): HTMLMsImpactElement;
  };

  interface HTMLMsRuneBalanceElement extends Components.MsRuneBalance, HTMLStencilElement {}
  var HTMLMsRuneBalanceElement: {
    prototype: HTMLMsRuneBalanceElement;
    new (): HTMLMsRuneBalanceElement;
  };

  interface HTMLMsRuneFocusElement extends Components.MsRuneFocus, HTMLStencilElement {}
  var HTMLMsRuneFocusElement: {
    prototype: HTMLMsRuneFocusElement;
    new (): HTMLMsRuneFocusElement;
  };

  interface HTMLMsStormSigilElement extends Components.MsStormSigil, HTMLStencilElement {}
  var HTMLMsStormSigilElement: {
    prototype: HTMLMsStormSigilElement;
    new (): HTMLMsStormSigilElement;
  };

  interface HTMLMsWardingRuneElement extends Components.MsWardingRune, HTMLStencilElement {}
  var HTMLMsWardingRuneElement: {
    prototype: HTMLMsWardingRuneElement;
    new (): HTMLMsWardingRuneElement;
  };

  interface HTMLMsWhirlingBladesElement extends Components.MsWhirlingBlades, HTMLStencilElement {}
  var HTMLMsWhirlingBladesElement: {
    prototype: HTMLMsWhirlingBladesElement;
    new (): HTMLMsWhirlingBladesElement;
  };

  interface HTMLMsArcaneBlastElement extends Components.MsArcaneBlast, HTMLStencilElement {}
  var HTMLMsArcaneBlastElement: {
    prototype: HTMLMsArcaneBlastElement;
    new (): HTMLMsArcaneBlastElement;
  };

  interface HTMLMsChainLightningElement extends Components.MsChainLightning, HTMLStencilElement {}
  var HTMLMsChainLightningElement: {
    prototype: HTMLMsChainLightningElement;
    new (): HTMLMsChainLightningElement;
  };

  interface HTMLMsCryomancyElement extends Components.MsCryomancy, HTMLStencilElement {}
  var HTMLMsCryomancyElement: {
    prototype: HTMLMsCryomancyElement;
    new (): HTMLMsCryomancyElement;
  };

  interface HTMLMsElectromancyElement extends Components.MsElectromancy, HTMLStencilElement {}
  var HTMLMsElectromancyElement: {
    prototype: HTMLMsElectromancyElement;
    new (): HTMLMsElectromancyElement;
  };

  interface HTMLMsElementalMasterElement extends Components.MsElementalMaster, HTMLStencilElement {}
  var HTMLMsElementalMasterElement: {
    prototype: HTMLMsElementalMasterElement;
    new (): HTMLMsElementalMasterElement;
  };

  interface HTMLMsFlameTornadoElement extends Components.MsFlameTornado, HTMLStencilElement {}
  var HTMLMsFlameTornadoElement: {
    prototype: HTMLMsFlameTornadoElement;
    new (): HTMLMsFlameTornadoElement;
  };

  interface HTMLMsFlameWaveElement extends Components.MsFlameWave, HTMLStencilElement {}
  var HTMLMsFlameWaveElement: {
    prototype: HTMLMsFlameWaveElement;
    new (): HTMLMsFlameWaveElement;
  };

  interface HTMLMsFocusSealElement extends Components.MsFocusSeal, HTMLStencilElement {}
  var HTMLMsFocusSealElement: {
    prototype: HTMLMsFocusSealElement;
    new (): HTMLMsFocusSealElement;
  };

  interface HTMLMsIceSpearElement extends Components.MsIceSpear, HTMLStencilElement {}
  var HTMLMsIceSpearElement: {
    prototype: HTMLMsIceSpearElement;
    new (): HTMLMsIceSpearElement;
  };

  interface HTMLMsIceStormElement extends Components.MsIceStorm, HTMLStencilElement {}
  var HTMLMsIceStormElement: {
    prototype: HTMLMsIceStormElement;
    new (): HTMLMsIceStormElement;
  };

  interface HTMLMsMagicArmorElement extends Components.MsMagicArmor, HTMLStencilElement {}
  var HTMLMsMagicArmorElement: {
    prototype: HTMLMsMagicArmorElement;
    new (): HTMLMsMagicArmorElement;
  };

  interface HTMLMsManaClawElement extends Components.MsManaClaw, HTMLStencilElement {}
  var HTMLMsManaClawElement: {
    prototype: HTMLMsManaClawElement;
    new (): HTMLMsManaClawElement;
  };

  interface HTMLMsManaFontElement extends Components.MsManaFont, HTMLStencilElement {}
  var HTMLMsManaFontElement: {
    prototype: HTMLMsManaFontElement;
    new (): HTMLMsManaFontElement;
  };

  interface HTMLMsPhantomClawElement extends Components.MsPhantomClaw, HTMLStencilElement {}
  var HTMLMsPhantomClawElement: {
    prototype: HTMLMsPhantomClawElement;
    new (): HTMLMsPhantomClawElement;
  };

  interface HTMLMsPyromancyElement extends Components.MsPyromancy, HTMLStencilElement {}
  var HTMLMsPyromancyElement: {
    prototype: HTMLMsPyromancyElement;
    new (): HTMLMsPyromancyElement;
  };

  interface HTMLMsTeleportElement extends Components.MsTeleport, HTMLStencilElement {}
  var HTMLMsTeleportElement: {
    prototype: HTMLMsTeleportElement;
    new (): HTMLMsTeleportElement;
  };

  interface HTMLMsThunderboltElement extends Components.MsThunderbolt, HTMLStencilElement {}
  var HTMLMsThunderboltElement: {
    prototype: HTMLMsThunderboltElement;
    new (): HTMLMsThunderboltElement;
  };

  interface HTMLElementTagNameMap {
    'ms-archer': HTMLMsArcherElement
    'ms-assassin': HTMLMsAssassinElement
    'ms-priest': HTMLMsPriestElement
    'ms-runeblade': HTMLMsRunebladeElement
    'ms-wizard': HTMLMsWizardElement
    'ms-archer-editor': HTMLMsArcherEditorElement
    'ms-assassin-editor': HTMLMsAssassinEditorElement
    'ms-priest-editor': HTMLMsPriestEditorElement
    'ms-runeblade-editor': HTMLMsRunebladeEditorElement
    'ms-wizard-editor': HTMLMsWizardEditorElement
    'ms-editor-outlet': HTMLMsEditorOutletElement
    'ms-editor': HTMLMsEditorElement
    'ms-level-control': HTMLMsLevelControlElement
    'ms-icon': HTMLMsIconElement
    'ms-skill-overlay': HTMLMsSkillOverlayElement
    'ms-agile-archer': HTMLMsAgileArcherElement
    'ms-arrow-barrage': HTMLMsArrowBarrageElement
    'ms-arrow-storm': HTMLMsArrowStormElement
    'ms-arrow-stream': HTMLMsArrowStreamElement
    'ms-bow-swing': HTMLMsBowSwingElement
    'ms-bronze-eagle': HTMLMsBronzeEagleElement
    'ms-conditioning': HTMLMsConditioningElement
    'ms-eagle-claw': HTMLMsEagleClawElement
    'ms-eagle-glide': HTMLMsEagleGlideElement
    'ms-eagles-majesty': HTMLMsEaglesMajestyElement
    'ms-evasive-salvo': HTMLMsEvasiveSalvoElement
    'ms-ice-arrow': HTMLMsIceArrowElement
    'ms-precision-shooter': HTMLMsPrecisionShooterElement
    'ms-rapid-shot': HTMLMsRapidShotElement
    'ms-screwdriver-shot': HTMLMsScrewdriverShotElement
    'ms-sharp-eyes': HTMLMsSharpEyesElement
    'ms-snipe': HTMLMsSnipeElement
    'ms-dark-cloak': HTMLMsDarkCloakElement
    'ms-dash': HTMLMsDashElement
    'ms-death-sentence': HTMLMsDeathSentenceElement
    'ms-fatal-strikes': HTMLMsFatalStrikesElement
    'ms-fragmented-star': HTMLMsFragmentedStarElement
    'ms-lucky-stars': HTMLMsLuckyStarsElement
    'ms-mark-of-death': HTMLMsMarkOfDeathElement
    'ms-mirror-image-dark-blade': HTMLMsMirrorImageDarkBladeElement
    'ms-shadow-arts': HTMLMsShadowArtsElement
    'ms-shadow-burst': HTMLMsShadowBurstElement
    'ms-shadow-chaser': HTMLMsShadowChaserElement
    'ms-shadow-cutter': HTMLMsShadowCutterElement
    'ms-shadow-web': HTMLMsShadowWebElement
    'ms-soul-grind': HTMLMsSoulGrindElement
    'ms-star-chaser': HTMLMsStarChaserElement
    'ms-star-flurry': HTMLMsStarFlurryElement
    'ms-thrown-weapon-mastery': HTMLMsThrownWeaponMasteryElement
    'ms-angelic-ray': HTMLMsAngelicRayElement
    'ms-celestial-blessings': HTMLMsCelestialBlessingsElement
    'ms-celestial-guardian': HTMLMsCelestialGuardianElement
    'ms-celestial-light': HTMLMsCelestialLightElement
    'ms-disciple': HTMLMsDiscipleElement
    'ms-healing-mastery': HTMLMsHealingMasteryElement
    'ms-healing-prayer': HTMLMsHealingPrayerElement
    'ms-heavenly-wings': HTMLMsHeavenlyWingsElement
    'ms-holy-blast': HTMLMsHolyBlastElement
    'ms-holy-relic': HTMLMsHolyRelicElement
    'ms-holy-symbol': HTMLMsHolySymbolElement
    'ms-sanctuary': HTMLMsSanctuaryElement
    'ms-scepter-mastery': HTMLMsScepterMasteryElement
    'ms-scourging-wave': HTMLMsScourgingWaveElement
    'ms-shield-of-the-archon': HTMLMsShieldOfTheArchonElement
    'ms-smiting-aura': HTMLMsSmitingAuraElement
    'ms-steadfast-faith': HTMLMsSteadfastFaithElement
    'ms-blade-chasm': HTMLMsBladeChasmElement
    'ms-blade-mastery': HTMLMsBladeMasteryElement
    'ms-blink': HTMLMsBlinkElement
    'ms-echoing-blade': HTMLMsEchoingBladeElement
    'ms-elemental-potency': HTMLMsElementalPotencyElement
    'ms-flame-sigil': HTMLMsFlameSigilElement
    'ms-flurry': HTMLMsFlurryElement
    'ms-frost-sigil': HTMLMsFrostSigilElement
    'ms-gravity-rune': HTMLMsGravityRuneElement
    'ms-honing-runes': HTMLMsHoningRunesElement
    'ms-illusory-blades': HTMLMsIllusoryBladesElement
    'ms-impact': HTMLMsImpactElement
    'ms-rune-balance': HTMLMsRuneBalanceElement
    'ms-rune-focus': HTMLMsRuneFocusElement
    'ms-storm-sigil': HTMLMsStormSigilElement
    'ms-warding-rune': HTMLMsWardingRuneElement
    'ms-whirling-blades': HTMLMsWhirlingBladesElement
    'ms-arcane-blast': HTMLMsArcaneBlastElement
    'ms-chain-lightning': HTMLMsChainLightningElement
    'ms-cryomancy': HTMLMsCryomancyElement
    'ms-electromancy': HTMLMsElectromancyElement
    'ms-elemental-master': HTMLMsElementalMasterElement
    'ms-flame-tornado': HTMLMsFlameTornadoElement
    'ms-flame-wave': HTMLMsFlameWaveElement
    'ms-focus-seal': HTMLMsFocusSealElement
    'ms-ice-spear': HTMLMsIceSpearElement
    'ms-ice-storm': HTMLMsIceStormElement
    'ms-magic-armor': HTMLMsMagicArmorElement
    'ms-mana-claw': HTMLMsManaClawElement
    'ms-mana-font': HTMLMsManaFontElement
    'ms-phantom-claw': HTMLMsPhantomClawElement
    'ms-pyromancy': HTMLMsPyromancyElement
    'ms-teleport': HTMLMsTeleportElement
    'ms-thunderbolt': HTMLMsThunderboltElement
  }

  interface ElementTagNameMap {
    'ms-archer': HTMLMsArcherElement;
    'ms-assassin': HTMLMsAssassinElement;
    'ms-priest': HTMLMsPriestElement;
    'ms-runeblade': HTMLMsRunebladeElement;
    'ms-wizard': HTMLMsWizardElement;
    'ms-archer-editor': HTMLMsArcherEditorElement;
    'ms-assassin-editor': HTMLMsAssassinEditorElement;
    'ms-priest-editor': HTMLMsPriestEditorElement;
    'ms-runeblade-editor': HTMLMsRunebladeEditorElement;
    'ms-wizard-editor': HTMLMsWizardEditorElement;
    'ms-editor-outlet': HTMLMsEditorOutletElement;
    'ms-editor': HTMLMsEditorElement;
    'ms-level-control': HTMLMsLevelControlElement;
    'ms-icon': HTMLMsIconElement;
    'ms-skill-overlay': HTMLMsSkillOverlayElement;
    'ms-agile-archer': HTMLMsAgileArcherElement;
    'ms-arrow-barrage': HTMLMsArrowBarrageElement;
    'ms-arrow-storm': HTMLMsArrowStormElement;
    'ms-arrow-stream': HTMLMsArrowStreamElement;
    'ms-bow-swing': HTMLMsBowSwingElement;
    'ms-bronze-eagle': HTMLMsBronzeEagleElement;
    'ms-conditioning': HTMLMsConditioningElement;
    'ms-eagle-claw': HTMLMsEagleClawElement;
    'ms-eagle-glide': HTMLMsEagleGlideElement;
    'ms-eagles-majesty': HTMLMsEaglesMajestyElement;
    'ms-evasive-salvo': HTMLMsEvasiveSalvoElement;
    'ms-ice-arrow': HTMLMsIceArrowElement;
    'ms-precision-shooter': HTMLMsPrecisionShooterElement;
    'ms-rapid-shot': HTMLMsRapidShotElement;
    'ms-screwdriver-shot': HTMLMsScrewdriverShotElement;
    'ms-sharp-eyes': HTMLMsSharpEyesElement;
    'ms-snipe': HTMLMsSnipeElement;
    'ms-dark-cloak': HTMLMsDarkCloakElement;
    'ms-dash': HTMLMsDashElement;
    'ms-death-sentence': HTMLMsDeathSentenceElement;
    'ms-fatal-strikes': HTMLMsFatalStrikesElement;
    'ms-fragmented-star': HTMLMsFragmentedStarElement;
    'ms-lucky-stars': HTMLMsLuckyStarsElement;
    'ms-mark-of-death': HTMLMsMarkOfDeathElement;
    'ms-mirror-image-dark-blade': HTMLMsMirrorImageDarkBladeElement;
    'ms-shadow-arts': HTMLMsShadowArtsElement;
    'ms-shadow-burst': HTMLMsShadowBurstElement;
    'ms-shadow-chaser': HTMLMsShadowChaserElement;
    'ms-shadow-cutter': HTMLMsShadowCutterElement;
    'ms-shadow-web': HTMLMsShadowWebElement;
    'ms-soul-grind': HTMLMsSoulGrindElement;
    'ms-star-chaser': HTMLMsStarChaserElement;
    'ms-star-flurry': HTMLMsStarFlurryElement;
    'ms-thrown-weapon-mastery': HTMLMsThrownWeaponMasteryElement;
    'ms-angelic-ray': HTMLMsAngelicRayElement;
    'ms-celestial-blessings': HTMLMsCelestialBlessingsElement;
    'ms-celestial-guardian': HTMLMsCelestialGuardianElement;
    'ms-celestial-light': HTMLMsCelestialLightElement;
    'ms-disciple': HTMLMsDiscipleElement;
    'ms-healing-mastery': HTMLMsHealingMasteryElement;
    'ms-healing-prayer': HTMLMsHealingPrayerElement;
    'ms-heavenly-wings': HTMLMsHeavenlyWingsElement;
    'ms-holy-blast': HTMLMsHolyBlastElement;
    'ms-holy-relic': HTMLMsHolyRelicElement;
    'ms-holy-symbol': HTMLMsHolySymbolElement;
    'ms-sanctuary': HTMLMsSanctuaryElement;
    'ms-scepter-mastery': HTMLMsScepterMasteryElement;
    'ms-scourging-wave': HTMLMsScourgingWaveElement;
    'ms-shield-of-the-archon': HTMLMsShieldOfTheArchonElement;
    'ms-smiting-aura': HTMLMsSmitingAuraElement;
    'ms-steadfast-faith': HTMLMsSteadfastFaithElement;
    'ms-blade-chasm': HTMLMsBladeChasmElement;
    'ms-blade-mastery': HTMLMsBladeMasteryElement;
    'ms-blink': HTMLMsBlinkElement;
    'ms-echoing-blade': HTMLMsEchoingBladeElement;
    'ms-elemental-potency': HTMLMsElementalPotencyElement;
    'ms-flame-sigil': HTMLMsFlameSigilElement;
    'ms-flurry': HTMLMsFlurryElement;
    'ms-frost-sigil': HTMLMsFrostSigilElement;
    'ms-gravity-rune': HTMLMsGravityRuneElement;
    'ms-honing-runes': HTMLMsHoningRunesElement;
    'ms-illusory-blades': HTMLMsIllusoryBladesElement;
    'ms-impact': HTMLMsImpactElement;
    'ms-rune-balance': HTMLMsRuneBalanceElement;
    'ms-rune-focus': HTMLMsRuneFocusElement;
    'ms-storm-sigil': HTMLMsStormSigilElement;
    'ms-warding-rune': HTMLMsWardingRuneElement;
    'ms-whirling-blades': HTMLMsWhirlingBladesElement;
    'ms-arcane-blast': HTMLMsArcaneBlastElement;
    'ms-chain-lightning': HTMLMsChainLightningElement;
    'ms-cryomancy': HTMLMsCryomancyElement;
    'ms-electromancy': HTMLMsElectromancyElement;
    'ms-elemental-master': HTMLMsElementalMasterElement;
    'ms-flame-tornado': HTMLMsFlameTornadoElement;
    'ms-flame-wave': HTMLMsFlameWaveElement;
    'ms-focus-seal': HTMLMsFocusSealElement;
    'ms-ice-spear': HTMLMsIceSpearElement;
    'ms-ice-storm': HTMLMsIceStormElement;
    'ms-magic-armor': HTMLMsMagicArmorElement;
    'ms-mana-claw': HTMLMsManaClawElement;
    'ms-mana-font': HTMLMsManaFontElement;
    'ms-phantom-claw': HTMLMsPhantomClawElement;
    'ms-pyromancy': HTMLMsPyromancyElement;
    'ms-teleport': HTMLMsTeleportElement;
    'ms-thunderbolt': HTMLMsThunderboltElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
