/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  MapleStoryClass,
} from './components/editor/editor.interfaces';


export namespace Components {

  interface MsArcher {
    'agileArcher': number;
    'arrowBarrage': number;
    'arrowStorm': number;
    'arrowStream': number;
    'bowSwing': number;
    'bronzeEagle': number;
    'conditioning': number;
    'eagleClaw': number;
    'eagleGlide': number;
    'eaglesMajesty': number;
    'evasiveSalvo': number;
    'iceArrow': number;
    'precisionShooter': number;
    'rapidShot': number;
    'screwdriverShot': number;
    'sharpEyes': number;
    'snipe': number;
  }
  interface MsArcherAttributes extends StencilHTMLAttributes {
    'agileArcher'?: number;
    'arrowBarrage'?: number;
    'arrowStorm'?: number;
    'arrowStream'?: number;
    'bowSwing'?: number;
    'bronzeEagle'?: number;
    'conditioning'?: number;
    'eagleClaw'?: number;
    'eagleGlide'?: number;
    'eaglesMajesty'?: number;
    'evasiveSalvo'?: number;
    'iceArrow'?: number;
    'precisionShooter'?: number;
    'rapidShot'?: number;
    'screwdriverShot'?: number;
    'sharpEyes'?: number;
    'snipe'?: number;
  }

  interface MsPriest {
    'angelicRay': number;
    'celestialBlessings': number;
    'celestialGuardian': number;
    'celestialLight': number;
    'disciple': number;
    'healingMastery': number;
    'healingPrayer': number;
    'heavenlyWings': number;
    'holyBlast': number;
    'holyRelic': number;
    'holySymbol': number;
    'sanctuary': number;
    'scepterMastery': number;
    'scourgingWave': number;
    'shieldOfTheArchon': number;
    'smitingAura': number;
    'steadfastFaith': number;
  }
  interface MsPriestAttributes extends StencilHTMLAttributes {
    'angelicRay'?: number;
    'celestialBlessings'?: number;
    'celestialGuardian'?: number;
    'celestialLight'?: number;
    'disciple'?: number;
    'healingMastery'?: number;
    'healingPrayer'?: number;
    'heavenlyWings'?: number;
    'holyBlast'?: number;
    'holyRelic'?: number;
    'holySymbol'?: number;
    'sanctuary'?: number;
    'scepterMastery'?: number;
    'scourgingWave'?: number;
    'shieldOfTheArchon'?: number;
    'smitingAura'?: number;
    'steadfastFaith'?: number;
  }

  interface MsArcherEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsArcherEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsPriestEditor {
    'toHtmlString': () => Promise<string>;
  }
  interface MsPriestEditorAttributes extends StencilHTMLAttributes {
    'onSkillchanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsEditorOutlet {
    'editor': string;
  }
  interface MsEditorOutletAttributes extends StencilHTMLAttributes {
    'editor'?: string;
  }

  interface MsEditor {
    'msClass': MapleStoryClass;
    'toHtmlString': () => string;
  }
  interface MsEditorAttributes extends StencilHTMLAttributes {
    'msClass'?: MapleStoryClass;
    'onChanged'?: (event: CustomEvent<string>) => void;
  }

  interface MsLevelControl {
    'level': number;
    'max': number;
    'min': number;
  }
  interface MsLevelControlAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
    'min'?: number;
    'onLevelchanged'?: (event: CustomEvent<number>) => void;
  }

  interface MsIcon {
    'name': string;
  }
  interface MsIconAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface MsSkillOverlay {
    'cooldown': number;
    'element': string;
    'heading': string;
    'level': number;
    'max': number;
    'passive': boolean;
    'requirements': string[];
    'spirit': number;
    'type': string;
    'weaponRequired': string;
  }
  interface MsSkillOverlayAttributes extends StencilHTMLAttributes {
    'cooldown'?: number;
    'element'?: string;
    'heading'?: string;
    'level'?: number;
    'max'?: number;
    'passive'?: boolean;
    'requirements'?: string[];
    'spirit'?: number;
    'type'?: string;
    'weaponRequired'?: string;
  }

  interface MsAgileArcher {
    'level': number;
    'max': number;
  }
  interface MsAgileArcherAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowBarrage {
    'level': number;
    'max': number;
  }
  interface MsArrowBarrageAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowStorm {
    'level': number;
    'max': number;
  }
  interface MsArrowStormAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsArrowStream {
    'level': number;
    'max': number;
  }
  interface MsArrowStreamAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBowSwing {
    'level': number;
    'max': number;
  }
  interface MsBowSwingAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsBronzeEagle {
    'level': number;
    'max': number;
  }
  interface MsBronzeEagleAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsConditioning {
    'level': number;
    'max': number;
  }
  interface MsConditioningAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEagleClaw {
    'level': number;
    'max': number;
  }
  interface MsEagleClawAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEagleGlide {
    'level': number;
    'max': number;
  }
  interface MsEagleGlideAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEaglesMajesty {
    'level': number;
    'max': number;
  }
  interface MsEaglesMajestyAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsEvasiveSalvo {
    'level': number;
    'max': number;
  }
  interface MsEvasiveSalvoAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsIceArrow {
    'level': number;
    'max': number;
  }
  interface MsIceArrowAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsPrecisionShooter {
    'level': number;
    'max': number;
  }
  interface MsPrecisionShooterAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsRapidShot {
    'level': number;
    'max': number;
  }
  interface MsRapidShotAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScrewdriverShot {
    'level': number;
    'max': number;
  }
  interface MsScrewdriverShotAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSharpEyes {
    'level': number;
    'max': number;
  }
  interface MsSharpEyesAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSnipe {
    'level': number;
    'max': number;
  }
  interface MsSnipeAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsAngelicRay {
    'level': number;
    'max': number;
  }
  interface MsAngelicRayAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialBlessings {
    'level': number;
    'max': number;
  }
  interface MsCelestialBlessingsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialGuardian {
    'level': number;
    'max': number;
  }
  interface MsCelestialGuardianAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsCelestialLight {
    'level': number;
    'max': number;
  }
  interface MsCelestialLightAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsDisciple {
    'level': number;
    'max': number;
  }
  interface MsDiscipleAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHealingMastery {
    'level': number;
    'max': number;
  }
  interface MsHealingMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHealingPrayer {
    'level': number;
    'max': number;
  }
  interface MsHealingPrayerAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHeavenlyWings {
    'level': number;
    'max': number;
  }
  interface MsHeavenlyWingsAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolyBlast {
    'level': number;
    'max': number;
  }
  interface MsHolyBlastAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolyRelic {
    'level': number;
    'max': number;
  }
  interface MsHolyRelicAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsHolySymbol {
    'level': number;
    'max': number;
  }
  interface MsHolySymbolAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSanctuary {
    'level': number;
    'max': number;
  }
  interface MsSanctuaryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScepterMastery {
    'level': number;
    'max': number;
  }
  interface MsScepterMasteryAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsScourgingWave {
    'level': number;
    'max': number;
  }
  interface MsScourgingWaveAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsShieldOfTheArchon {
    'level': number;
    'max': number;
  }
  interface MsShieldOfTheArchonAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSmitingAura {
    'level': number;
    'max': number;
  }
  interface MsSmitingAuraAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }

  interface MsSteadfastFaith {
    'level': number;
    'max': number;
  }
  interface MsSteadfastFaithAttributes extends StencilHTMLAttributes {
    'level'?: number;
    'max'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MsArcher': Components.MsArcher;
    'MsPriest': Components.MsPriest;
    'MsArcherEditor': Components.MsArcherEditor;
    'MsPriestEditor': Components.MsPriestEditor;
    'MsEditorOutlet': Components.MsEditorOutlet;
    'MsEditor': Components.MsEditor;
    'MsLevelControl': Components.MsLevelControl;
    'MsIcon': Components.MsIcon;
    'MsSkillOverlay': Components.MsSkillOverlay;
    'MsAgileArcher': Components.MsAgileArcher;
    'MsArrowBarrage': Components.MsArrowBarrage;
    'MsArrowStorm': Components.MsArrowStorm;
    'MsArrowStream': Components.MsArrowStream;
    'MsBowSwing': Components.MsBowSwing;
    'MsBronzeEagle': Components.MsBronzeEagle;
    'MsConditioning': Components.MsConditioning;
    'MsEagleClaw': Components.MsEagleClaw;
    'MsEagleGlide': Components.MsEagleGlide;
    'MsEaglesMajesty': Components.MsEaglesMajesty;
    'MsEvasiveSalvo': Components.MsEvasiveSalvo;
    'MsIceArrow': Components.MsIceArrow;
    'MsPrecisionShooter': Components.MsPrecisionShooter;
    'MsRapidShot': Components.MsRapidShot;
    'MsScrewdriverShot': Components.MsScrewdriverShot;
    'MsSharpEyes': Components.MsSharpEyes;
    'MsSnipe': Components.MsSnipe;
    'MsAngelicRay': Components.MsAngelicRay;
    'MsCelestialBlessings': Components.MsCelestialBlessings;
    'MsCelestialGuardian': Components.MsCelestialGuardian;
    'MsCelestialLight': Components.MsCelestialLight;
    'MsDisciple': Components.MsDisciple;
    'MsHealingMastery': Components.MsHealingMastery;
    'MsHealingPrayer': Components.MsHealingPrayer;
    'MsHeavenlyWings': Components.MsHeavenlyWings;
    'MsHolyBlast': Components.MsHolyBlast;
    'MsHolyRelic': Components.MsHolyRelic;
    'MsHolySymbol': Components.MsHolySymbol;
    'MsSanctuary': Components.MsSanctuary;
    'MsScepterMastery': Components.MsScepterMastery;
    'MsScourgingWave': Components.MsScourgingWave;
    'MsShieldOfTheArchon': Components.MsShieldOfTheArchon;
    'MsSmitingAura': Components.MsSmitingAura;
    'MsSteadfastFaith': Components.MsSteadfastFaith;
  }

  interface StencilIntrinsicElements {
    'ms-archer': Components.MsArcherAttributes;
    'ms-priest': Components.MsPriestAttributes;
    'ms-archer-editor': Components.MsArcherEditorAttributes;
    'ms-priest-editor': Components.MsPriestEditorAttributes;
    'ms-editor-outlet': Components.MsEditorOutletAttributes;
    'ms-editor': Components.MsEditorAttributes;
    'ms-level-control': Components.MsLevelControlAttributes;
    'ms-icon': Components.MsIconAttributes;
    'ms-skill-overlay': Components.MsSkillOverlayAttributes;
    'ms-agile-archer': Components.MsAgileArcherAttributes;
    'ms-arrow-barrage': Components.MsArrowBarrageAttributes;
    'ms-arrow-storm': Components.MsArrowStormAttributes;
    'ms-arrow-stream': Components.MsArrowStreamAttributes;
    'ms-bow-swing': Components.MsBowSwingAttributes;
    'ms-bronze-eagle': Components.MsBronzeEagleAttributes;
    'ms-conditioning': Components.MsConditioningAttributes;
    'ms-eagle-claw': Components.MsEagleClawAttributes;
    'ms-eagle-glide': Components.MsEagleGlideAttributes;
    'ms-eagles-majesty': Components.MsEaglesMajestyAttributes;
    'ms-evasive-salvo': Components.MsEvasiveSalvoAttributes;
    'ms-ice-arrow': Components.MsIceArrowAttributes;
    'ms-precision-shooter': Components.MsPrecisionShooterAttributes;
    'ms-rapid-shot': Components.MsRapidShotAttributes;
    'ms-screwdriver-shot': Components.MsScrewdriverShotAttributes;
    'ms-sharp-eyes': Components.MsSharpEyesAttributes;
    'ms-snipe': Components.MsSnipeAttributes;
    'ms-angelic-ray': Components.MsAngelicRayAttributes;
    'ms-celestial-blessings': Components.MsCelestialBlessingsAttributes;
    'ms-celestial-guardian': Components.MsCelestialGuardianAttributes;
    'ms-celestial-light': Components.MsCelestialLightAttributes;
    'ms-disciple': Components.MsDiscipleAttributes;
    'ms-healing-mastery': Components.MsHealingMasteryAttributes;
    'ms-healing-prayer': Components.MsHealingPrayerAttributes;
    'ms-heavenly-wings': Components.MsHeavenlyWingsAttributes;
    'ms-holy-blast': Components.MsHolyBlastAttributes;
    'ms-holy-relic': Components.MsHolyRelicAttributes;
    'ms-holy-symbol': Components.MsHolySymbolAttributes;
    'ms-sanctuary': Components.MsSanctuaryAttributes;
    'ms-scepter-mastery': Components.MsScepterMasteryAttributes;
    'ms-scourging-wave': Components.MsScourgingWaveAttributes;
    'ms-shield-of-the-archon': Components.MsShieldOfTheArchonAttributes;
    'ms-smiting-aura': Components.MsSmitingAuraAttributes;
    'ms-steadfast-faith': Components.MsSteadfastFaithAttributes;
  }


  interface HTMLMsArcherElement extends Components.MsArcher, HTMLStencilElement {}
  var HTMLMsArcherElement: {
    prototype: HTMLMsArcherElement;
    new (): HTMLMsArcherElement;
  };

  interface HTMLMsPriestElement extends Components.MsPriest, HTMLStencilElement {}
  var HTMLMsPriestElement: {
    prototype: HTMLMsPriestElement;
    new (): HTMLMsPriestElement;
  };

  interface HTMLMsArcherEditorElement extends Components.MsArcherEditor, HTMLStencilElement {}
  var HTMLMsArcherEditorElement: {
    prototype: HTMLMsArcherEditorElement;
    new (): HTMLMsArcherEditorElement;
  };

  interface HTMLMsPriestEditorElement extends Components.MsPriestEditor, HTMLStencilElement {}
  var HTMLMsPriestEditorElement: {
    prototype: HTMLMsPriestEditorElement;
    new (): HTMLMsPriestEditorElement;
  };

  interface HTMLMsEditorOutletElement extends Components.MsEditorOutlet, HTMLStencilElement {}
  var HTMLMsEditorOutletElement: {
    prototype: HTMLMsEditorOutletElement;
    new (): HTMLMsEditorOutletElement;
  };

  interface HTMLMsEditorElement extends Components.MsEditor, HTMLStencilElement {}
  var HTMLMsEditorElement: {
    prototype: HTMLMsEditorElement;
    new (): HTMLMsEditorElement;
  };

  interface HTMLMsLevelControlElement extends Components.MsLevelControl, HTMLStencilElement {}
  var HTMLMsLevelControlElement: {
    prototype: HTMLMsLevelControlElement;
    new (): HTMLMsLevelControlElement;
  };

  interface HTMLMsIconElement extends Components.MsIcon, HTMLStencilElement {}
  var HTMLMsIconElement: {
    prototype: HTMLMsIconElement;
    new (): HTMLMsIconElement;
  };

  interface HTMLMsSkillOverlayElement extends Components.MsSkillOverlay, HTMLStencilElement {}
  var HTMLMsSkillOverlayElement: {
    prototype: HTMLMsSkillOverlayElement;
    new (): HTMLMsSkillOverlayElement;
  };

  interface HTMLMsAgileArcherElement extends Components.MsAgileArcher, HTMLStencilElement {}
  var HTMLMsAgileArcherElement: {
    prototype: HTMLMsAgileArcherElement;
    new (): HTMLMsAgileArcherElement;
  };

  interface HTMLMsArrowBarrageElement extends Components.MsArrowBarrage, HTMLStencilElement {}
  var HTMLMsArrowBarrageElement: {
    prototype: HTMLMsArrowBarrageElement;
    new (): HTMLMsArrowBarrageElement;
  };

  interface HTMLMsArrowStormElement extends Components.MsArrowStorm, HTMLStencilElement {}
  var HTMLMsArrowStormElement: {
    prototype: HTMLMsArrowStormElement;
    new (): HTMLMsArrowStormElement;
  };

  interface HTMLMsArrowStreamElement extends Components.MsArrowStream, HTMLStencilElement {}
  var HTMLMsArrowStreamElement: {
    prototype: HTMLMsArrowStreamElement;
    new (): HTMLMsArrowStreamElement;
  };

  interface HTMLMsBowSwingElement extends Components.MsBowSwing, HTMLStencilElement {}
  var HTMLMsBowSwingElement: {
    prototype: HTMLMsBowSwingElement;
    new (): HTMLMsBowSwingElement;
  };

  interface HTMLMsBronzeEagleElement extends Components.MsBronzeEagle, HTMLStencilElement {}
  var HTMLMsBronzeEagleElement: {
    prototype: HTMLMsBronzeEagleElement;
    new (): HTMLMsBronzeEagleElement;
  };

  interface HTMLMsConditioningElement extends Components.MsConditioning, HTMLStencilElement {}
  var HTMLMsConditioningElement: {
    prototype: HTMLMsConditioningElement;
    new (): HTMLMsConditioningElement;
  };

  interface HTMLMsEagleClawElement extends Components.MsEagleClaw, HTMLStencilElement {}
  var HTMLMsEagleClawElement: {
    prototype: HTMLMsEagleClawElement;
    new (): HTMLMsEagleClawElement;
  };

  interface HTMLMsEagleGlideElement extends Components.MsEagleGlide, HTMLStencilElement {}
  var HTMLMsEagleGlideElement: {
    prototype: HTMLMsEagleGlideElement;
    new (): HTMLMsEagleGlideElement;
  };

  interface HTMLMsEaglesMajestyElement extends Components.MsEaglesMajesty, HTMLStencilElement {}
  var HTMLMsEaglesMajestyElement: {
    prototype: HTMLMsEaglesMajestyElement;
    new (): HTMLMsEaglesMajestyElement;
  };

  interface HTMLMsEvasiveSalvoElement extends Components.MsEvasiveSalvo, HTMLStencilElement {}
  var HTMLMsEvasiveSalvoElement: {
    prototype: HTMLMsEvasiveSalvoElement;
    new (): HTMLMsEvasiveSalvoElement;
  };

  interface HTMLMsIceArrowElement extends Components.MsIceArrow, HTMLStencilElement {}
  var HTMLMsIceArrowElement: {
    prototype: HTMLMsIceArrowElement;
    new (): HTMLMsIceArrowElement;
  };

  interface HTMLMsPrecisionShooterElement extends Components.MsPrecisionShooter, HTMLStencilElement {}
  var HTMLMsPrecisionShooterElement: {
    prototype: HTMLMsPrecisionShooterElement;
    new (): HTMLMsPrecisionShooterElement;
  };

  interface HTMLMsRapidShotElement extends Components.MsRapidShot, HTMLStencilElement {}
  var HTMLMsRapidShotElement: {
    prototype: HTMLMsRapidShotElement;
    new (): HTMLMsRapidShotElement;
  };

  interface HTMLMsScrewdriverShotElement extends Components.MsScrewdriverShot, HTMLStencilElement {}
  var HTMLMsScrewdriverShotElement: {
    prototype: HTMLMsScrewdriverShotElement;
    new (): HTMLMsScrewdriverShotElement;
  };

  interface HTMLMsSharpEyesElement extends Components.MsSharpEyes, HTMLStencilElement {}
  var HTMLMsSharpEyesElement: {
    prototype: HTMLMsSharpEyesElement;
    new (): HTMLMsSharpEyesElement;
  };

  interface HTMLMsSnipeElement extends Components.MsSnipe, HTMLStencilElement {}
  var HTMLMsSnipeElement: {
    prototype: HTMLMsSnipeElement;
    new (): HTMLMsSnipeElement;
  };

  interface HTMLMsAngelicRayElement extends Components.MsAngelicRay, HTMLStencilElement {}
  var HTMLMsAngelicRayElement: {
    prototype: HTMLMsAngelicRayElement;
    new (): HTMLMsAngelicRayElement;
  };

  interface HTMLMsCelestialBlessingsElement extends Components.MsCelestialBlessings, HTMLStencilElement {}
  var HTMLMsCelestialBlessingsElement: {
    prototype: HTMLMsCelestialBlessingsElement;
    new (): HTMLMsCelestialBlessingsElement;
  };

  interface HTMLMsCelestialGuardianElement extends Components.MsCelestialGuardian, HTMLStencilElement {}
  var HTMLMsCelestialGuardianElement: {
    prototype: HTMLMsCelestialGuardianElement;
    new (): HTMLMsCelestialGuardianElement;
  };

  interface HTMLMsCelestialLightElement extends Components.MsCelestialLight, HTMLStencilElement {}
  var HTMLMsCelestialLightElement: {
    prototype: HTMLMsCelestialLightElement;
    new (): HTMLMsCelestialLightElement;
  };

  interface HTMLMsDiscipleElement extends Components.MsDisciple, HTMLStencilElement {}
  var HTMLMsDiscipleElement: {
    prototype: HTMLMsDiscipleElement;
    new (): HTMLMsDiscipleElement;
  };

  interface HTMLMsHealingMasteryElement extends Components.MsHealingMastery, HTMLStencilElement {}
  var HTMLMsHealingMasteryElement: {
    prototype: HTMLMsHealingMasteryElement;
    new (): HTMLMsHealingMasteryElement;
  };

  interface HTMLMsHealingPrayerElement extends Components.MsHealingPrayer, HTMLStencilElement {}
  var HTMLMsHealingPrayerElement: {
    prototype: HTMLMsHealingPrayerElement;
    new (): HTMLMsHealingPrayerElement;
  };

  interface HTMLMsHeavenlyWingsElement extends Components.MsHeavenlyWings, HTMLStencilElement {}
  var HTMLMsHeavenlyWingsElement: {
    prototype: HTMLMsHeavenlyWingsElement;
    new (): HTMLMsHeavenlyWingsElement;
  };

  interface HTMLMsHolyBlastElement extends Components.MsHolyBlast, HTMLStencilElement {}
  var HTMLMsHolyBlastElement: {
    prototype: HTMLMsHolyBlastElement;
    new (): HTMLMsHolyBlastElement;
  };

  interface HTMLMsHolyRelicElement extends Components.MsHolyRelic, HTMLStencilElement {}
  var HTMLMsHolyRelicElement: {
    prototype: HTMLMsHolyRelicElement;
    new (): HTMLMsHolyRelicElement;
  };

  interface HTMLMsHolySymbolElement extends Components.MsHolySymbol, HTMLStencilElement {}
  var HTMLMsHolySymbolElement: {
    prototype: HTMLMsHolySymbolElement;
    new (): HTMLMsHolySymbolElement;
  };

  interface HTMLMsSanctuaryElement extends Components.MsSanctuary, HTMLStencilElement {}
  var HTMLMsSanctuaryElement: {
    prototype: HTMLMsSanctuaryElement;
    new (): HTMLMsSanctuaryElement;
  };

  interface HTMLMsScepterMasteryElement extends Components.MsScepterMastery, HTMLStencilElement {}
  var HTMLMsScepterMasteryElement: {
    prototype: HTMLMsScepterMasteryElement;
    new (): HTMLMsScepterMasteryElement;
  };

  interface HTMLMsScourgingWaveElement extends Components.MsScourgingWave, HTMLStencilElement {}
  var HTMLMsScourgingWaveElement: {
    prototype: HTMLMsScourgingWaveElement;
    new (): HTMLMsScourgingWaveElement;
  };

  interface HTMLMsShieldOfTheArchonElement extends Components.MsShieldOfTheArchon, HTMLStencilElement {}
  var HTMLMsShieldOfTheArchonElement: {
    prototype: HTMLMsShieldOfTheArchonElement;
    new (): HTMLMsShieldOfTheArchonElement;
  };

  interface HTMLMsSmitingAuraElement extends Components.MsSmitingAura, HTMLStencilElement {}
  var HTMLMsSmitingAuraElement: {
    prototype: HTMLMsSmitingAuraElement;
    new (): HTMLMsSmitingAuraElement;
  };

  interface HTMLMsSteadfastFaithElement extends Components.MsSteadfastFaith, HTMLStencilElement {}
  var HTMLMsSteadfastFaithElement: {
    prototype: HTMLMsSteadfastFaithElement;
    new (): HTMLMsSteadfastFaithElement;
  };

  interface HTMLElementTagNameMap {
    'ms-archer': HTMLMsArcherElement
    'ms-priest': HTMLMsPriestElement
    'ms-archer-editor': HTMLMsArcherEditorElement
    'ms-priest-editor': HTMLMsPriestEditorElement
    'ms-editor-outlet': HTMLMsEditorOutletElement
    'ms-editor': HTMLMsEditorElement
    'ms-level-control': HTMLMsLevelControlElement
    'ms-icon': HTMLMsIconElement
    'ms-skill-overlay': HTMLMsSkillOverlayElement
    'ms-agile-archer': HTMLMsAgileArcherElement
    'ms-arrow-barrage': HTMLMsArrowBarrageElement
    'ms-arrow-storm': HTMLMsArrowStormElement
    'ms-arrow-stream': HTMLMsArrowStreamElement
    'ms-bow-swing': HTMLMsBowSwingElement
    'ms-bronze-eagle': HTMLMsBronzeEagleElement
    'ms-conditioning': HTMLMsConditioningElement
    'ms-eagle-claw': HTMLMsEagleClawElement
    'ms-eagle-glide': HTMLMsEagleGlideElement
    'ms-eagles-majesty': HTMLMsEaglesMajestyElement
    'ms-evasive-salvo': HTMLMsEvasiveSalvoElement
    'ms-ice-arrow': HTMLMsIceArrowElement
    'ms-precision-shooter': HTMLMsPrecisionShooterElement
    'ms-rapid-shot': HTMLMsRapidShotElement
    'ms-screwdriver-shot': HTMLMsScrewdriverShotElement
    'ms-sharp-eyes': HTMLMsSharpEyesElement
    'ms-snipe': HTMLMsSnipeElement
    'ms-angelic-ray': HTMLMsAngelicRayElement
    'ms-celestial-blessings': HTMLMsCelestialBlessingsElement
    'ms-celestial-guardian': HTMLMsCelestialGuardianElement
    'ms-celestial-light': HTMLMsCelestialLightElement
    'ms-disciple': HTMLMsDiscipleElement
    'ms-healing-mastery': HTMLMsHealingMasteryElement
    'ms-healing-prayer': HTMLMsHealingPrayerElement
    'ms-heavenly-wings': HTMLMsHeavenlyWingsElement
    'ms-holy-blast': HTMLMsHolyBlastElement
    'ms-holy-relic': HTMLMsHolyRelicElement
    'ms-holy-symbol': HTMLMsHolySymbolElement
    'ms-sanctuary': HTMLMsSanctuaryElement
    'ms-scepter-mastery': HTMLMsScepterMasteryElement
    'ms-scourging-wave': HTMLMsScourgingWaveElement
    'ms-shield-of-the-archon': HTMLMsShieldOfTheArchonElement
    'ms-smiting-aura': HTMLMsSmitingAuraElement
    'ms-steadfast-faith': HTMLMsSteadfastFaithElement
  }

  interface ElementTagNameMap {
    'ms-archer': HTMLMsArcherElement;
    'ms-priest': HTMLMsPriestElement;
    'ms-archer-editor': HTMLMsArcherEditorElement;
    'ms-priest-editor': HTMLMsPriestEditorElement;
    'ms-editor-outlet': HTMLMsEditorOutletElement;
    'ms-editor': HTMLMsEditorElement;
    'ms-level-control': HTMLMsLevelControlElement;
    'ms-icon': HTMLMsIconElement;
    'ms-skill-overlay': HTMLMsSkillOverlayElement;
    'ms-agile-archer': HTMLMsAgileArcherElement;
    'ms-arrow-barrage': HTMLMsArrowBarrageElement;
    'ms-arrow-storm': HTMLMsArrowStormElement;
    'ms-arrow-stream': HTMLMsArrowStreamElement;
    'ms-bow-swing': HTMLMsBowSwingElement;
    'ms-bronze-eagle': HTMLMsBronzeEagleElement;
    'ms-conditioning': HTMLMsConditioningElement;
    'ms-eagle-claw': HTMLMsEagleClawElement;
    'ms-eagle-glide': HTMLMsEagleGlideElement;
    'ms-eagles-majesty': HTMLMsEaglesMajestyElement;
    'ms-evasive-salvo': HTMLMsEvasiveSalvoElement;
    'ms-ice-arrow': HTMLMsIceArrowElement;
    'ms-precision-shooter': HTMLMsPrecisionShooterElement;
    'ms-rapid-shot': HTMLMsRapidShotElement;
    'ms-screwdriver-shot': HTMLMsScrewdriverShotElement;
    'ms-sharp-eyes': HTMLMsSharpEyesElement;
    'ms-snipe': HTMLMsSnipeElement;
    'ms-angelic-ray': HTMLMsAngelicRayElement;
    'ms-celestial-blessings': HTMLMsCelestialBlessingsElement;
    'ms-celestial-guardian': HTMLMsCelestialGuardianElement;
    'ms-celestial-light': HTMLMsCelestialLightElement;
    'ms-disciple': HTMLMsDiscipleElement;
    'ms-healing-mastery': HTMLMsHealingMasteryElement;
    'ms-healing-prayer': HTMLMsHealingPrayerElement;
    'ms-heavenly-wings': HTMLMsHeavenlyWingsElement;
    'ms-holy-blast': HTMLMsHolyBlastElement;
    'ms-holy-relic': HTMLMsHolyRelicElement;
    'ms-holy-symbol': HTMLMsHolySymbolElement;
    'ms-sanctuary': HTMLMsSanctuaryElement;
    'ms-scepter-mastery': HTMLMsScepterMasteryElement;
    'ms-scourging-wave': HTMLMsScourgingWaveElement;
    'ms-shield-of-the-archon': HTMLMsShieldOfTheArchonElement;
    'ms-smiting-aura': HTMLMsSmitingAuraElement;
    'ms-steadfast-faith': HTMLMsSteadfastFaithElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
